# Generated by Django 3.0.2 on 2020-01-14 06:22

import attendees.persons.models.utility
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.contrib.postgres.fields.jsonb import JSONField
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whereabouts', '0004_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(verbose_name='used by', on_delete=models.SET(0), to='whereabouts.Organization', help_text='which organization use this?')),
                ('display_name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=50, unique=True)),
                ('infos', JSONField(blank=True, default=dict, help_text='Example: {"hostname": "where the app deployed"}. Please keep {} here even no data', null=True)),

            ],
            options={
                'db_table': 'whereabouts_campus',
                'verbose_name_plural': 'Campuses',
            },
            bases=(models.Model, attendees.persons.models.utility.Utility),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=django.contrib.postgres.indexes.GinIndex(fields=['infos'], name='campus_infos_gin'),
        ),
    ]
