version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django_local: &django_local
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: attendees_local_django
    container_name: django_local
    depends_on:
      - postgres_local
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.sendgrid.env
    ports:
      - "8000:8000"
    command: /start

  postgres_local:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: attendees_local_postgres
    container_name: postgres_local
    ports:
      - "5433:5432"  # for local and production run simultaneously
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    platform: linux/amd64
    image: attendees_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./attendees:/app/attendees:z
    ports:
      - "7000:7000"
    command: /start-docs

  mailhog:
    platform: linux/amd64
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: redis

  celeryworker_local:
    <<: *django_local
    image: attendees_local_celeryworker
    container_name: celeryworker_local
    depends_on:
      - redis
      - postgres_local
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat_local:
    <<: *django_local
    image: attendees_local_celerybeat
    container_name: celerybeat_local
    depends_on:
      - redis
      - postgres_local
      - mailhog
    ports: []
    command: /start-celerybeat

  flower_local:
    <<: *django_local
    image: attendees_local_flower
    container_name: flower_local
    ports:
      - "5555:5555"
    command: /start-flower
