#!/bin/bash

set -o errexit
set -o nounset

echo "hi jack 6"
echo "${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"

celery \
    -A config.celery_app \
    -b "${CELERY_BROKER_URL}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
