# Generated by Django 3.0.2 on 2020-02-19 03:00

from django.db import migrations, models
# from django.contrib.postgres.fields.jsonb import JSONField
from django.contrib.postgres.indexes import GinIndex

from attendees.persons.models import Utility


class Migration(migrations.Migration):

    dependencies = [
        ('whereabouts', '0003_organization'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(null=True, blank=True, default=None, help_text='Primary organization of the user', on_delete=models.SET_NULL, to='whereabouts.Organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='infos',
            field=models.JSONField(default=Utility.user_infos, null=True, blank=True, help_text="please keep {} here even there's no data"),
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=GinIndex(fields=['infos'], name='user_infos_gin'),
        ),
    ]
