# Generated by Django 3.2.11 on 2022-03-05 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from attendees.persons.models import Utility


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0004_auto_20220906_1625'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_menu_auth_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupsHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('user', models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='auth.group')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
        ),
        migrations.RunSQL(Utility.pgh_default_sql('users_usergroupshistory', original_model_table='users_user_groups')),
    ]
