# Generated by Django 3.2.11 on 2022-03-05 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from attendees.persons.models import Utility


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pghistory', '0004_auto_20220906_1625'),
        ('users', '0006_permissions_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissionProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user_user_permissions',),
        ),
        migrations.CreateModel(
            name='UserPermissionsHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('user', models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='auth.permission')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
        ),
        migrations.RunSQL(Utility.pgh_default_sql('users_userpermissionshistory', original_model_table='users_user_user_permissions')),
        pgtrigger.migrations.AddTrigger(
            model_name='userpermissionproxy',
            trigger=pgtrigger.compiler.Trigger(name='user_permission_add', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userpermissionshistory" ("user_id", "permission_id", "id", "pgh_created_at", "pgh_label", "pgh_context_id") VALUES (NEW."user_id", NEW."permission_id", NEW."id", NOW(), \'user_permission.add\', _pgh_attach_context()); RETURN NULL;', hash='81f3a1652aec793aac9c78d97285bf4c481aa15b', operation='INSERT', pgid='pgtrigger_user_permission_add_28bab', table='users_user_user_permissions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userpermissionproxy',
            trigger=pgtrigger.compiler.Trigger(name='user_permission_remove', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userpermissionshistory" ("user_id", "permission_id", "id", "pgh_created_at", "pgh_label", "pgh_context_id") VALUES (OLD."user_id", OLD."permission_id", OLD."id", NOW(), \'user_permission.remove\', _pgh_attach_context()); RETURN NULL;', hash='378b79f59f78df11951781e5f7aa9450b75c65f1', operation='DELETE', pgid='pgtrigger_user_permission_remove_05537', table='users_user_user_permissions', when='AFTER')),
        ),
    ]
