# Generated by Django 3.2.11 on 2022-04-08 19:41

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from attendees.persons.models import Utility


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pghistory', '0004_auto_20220906_1625'),
        ('users', '0008_groups_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermissionProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group_permissions',),
        ),
        migrations.CreateModel(
            name='GroupPermissionsHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField()),
                ('group', models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='auth.group')),
                ('permission', models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='auth.permission')),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('users_grouppermissionshistory', original_model_table='auth_group_permissions')),
        pgtrigger.migrations.AddTrigger(
            model_name='grouppermissionproxy',
            trigger=pgtrigger.compiler.Trigger(name='permission_add', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_grouppermissionshistory" ("group_id", "permission_id", "id", "pgh_created_at", "pgh_label", "pgh_context_id") VALUES (NEW."group_id", NEW."permission_id", NEW."id", NOW(), \'permission.add\', _pgh_attach_context()); RETURN NULL;', hash='04593aff93fe26f4cb786d3c47cb040988e58913', operation='INSERT', pgid='pgtrigger_permission_add_1ac45', table='auth_group_permissions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='grouppermissionproxy',
            trigger=pgtrigger.compiler.Trigger(name='permission_remove', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_grouppermissionshistory" ("group_id", "permission_id", "id", "pgh_created_at", "pgh_label", "pgh_context_id") VALUES (OLD."group_id", OLD."permission_id", OLD."id", NOW(), \'permission.remove\', _pgh_attach_context()); RETURN NULL;', hash='d2309c30b9d8d90242595c73b7edd6bb3833b79f', operation='DELETE', pgid='pgtrigger_permission_remove_82667', table='auth_group_permissions', when='AFTER')),
        ),
    ]
