# Generated by Django 3.2.11 on 2022-04-10 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from attendees.persons.models import Utility


class Migration(migrations.Migration):
    """
    If django-allauth uses email service not on the host, there probably won't be any records
    in account_emailconfirmation table. This tracking is just in case of switching email service.
    """

    dependencies = [
        ('pghistory', '0003_auto_20201023_1636'),
        ('account', '0002_email_max_length'),
        ('users', '0009_emailaddress_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmationHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='history', to='account.emailconfirmation')),
                ('id', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('sent', models.DateTimeField(null=True, verbose_name='sent')),
                ('key', models.CharField(max_length=64, verbose_name='key')),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('email_address', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='account.emailaddress', verbose_name='e-mail address')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('users_emailconfirmationhistory', original_model_table='account_emailconfirmation')),
    ]
