# Generated by Django 3.2.25 on 2026-06-04 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_emailaddress_unique_primary_email'),
        ('users', '0011_emailconfirmation_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddresshistory',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationhistory',
            name='email_address',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='account.emailaddress', verbose_name='email address'),
        ),
    ]
