# Generated by Django 4.2.13 on 2026-06-12 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0009_emailaddress_unique_primary_email'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0012_auto_20260604_0619'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='emailaddressproxy',
            name='emailaddress_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='emailconfirmationproxy',
            name='emailconfirmation_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='groupproxy',
            name='group_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='menu',
            name='menu_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='menuauthgroup',
            name='menuauthgroup_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='permissionproxy',
            name='permission_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='user',
            name='user_snapshot_update',
        ),
        migrations.AlterField(
            model_name='emailaddresshistory',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationhistory',
            name='email_address',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='account.emailaddress', verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='grouppermissionshistory',
            name='group',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Group_permissions+', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='grouppermissionshistory',
            name='permission',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Group_permissions+', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='permissionshistory',
            name='content_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='usergroupshistory',
            name='group',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_groups+', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usergroupshistory',
            name='user',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_groups+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpermissionshistory',
            name='permission',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_user_permissions+', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='userpermissionshistory',
            name='user',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_user_permissions+', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='emailaddressproxy',
            trigger=pgtrigger.compiler.Trigger(name='emailaddress_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."verified" IS DISTINCT FROM (NEW."verified") OR OLD."primary" IS DISTINCT FROM (NEW."primary") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "users_emailaddresshistory" ("user_id", "email", "verified", "primary", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."user_id", NEW."email", NEW."verified", NEW."primary", NEW."id", NOW(), \'emailaddress.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='22d5e9a1878dc05592112eaeb3370f6b204b9aab', operation='UPDATE', pgid='pgtrigger_emailaddress_snapshot_update_3a334', table='account_emailaddress', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='emailconfirmationproxy',
            trigger=pgtrigger.compiler.Trigger(name='emailconfirmation_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."email_address_id" IS DISTINCT FROM (NEW."email_address_id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."sent" IS DISTINCT FROM (NEW."sent") OR OLD."key" IS DISTINCT FROM (NEW."key") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "users_emailconfirmationhistory" ("email_address_id", "created", "sent", "key", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."email_address_id", NEW."created", NEW."sent", NEW."key", NEW."id", NOW(), \'emailconfirmation.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='40a942316fab1e98ad291fbb59add1cf268552d6', operation='UPDATE', pgid='pgtrigger_emailconfirmation_snapshot_update_fb7b9', table='account_emailconfirmation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupproxy',
            trigger=pgtrigger.compiler.Trigger(name='group_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "users_groupshistory" ("name", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."name", NEW."id", NOW(), \'group.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='d14c9178919a170f52d1e60abd3bfcf564533356', operation='UPDATE', pgid='pgtrigger_group_snapshot_update_adcdd', table='auth_group', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='menu',
            trigger=pgtrigger.compiler.Trigger(name='menu_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."organization_id" IS DISTINCT FROM (NEW."organization_id") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."tree_id" IS DISTINCT FROM (NEW."tree_id") OR OLD."level" IS DISTINCT FROM (NEW."level") OR OLD."lft" IS DISTINCT FROM (NEW."lft") OR OLD."rght" IS DISTINCT FROM (NEW."rght") OR OLD."display_order" IS DISTINCT FROM (NEW."display_order") OR OLD."category" IS DISTINCT FROM (NEW."category") OR OLD."url_name" IS DISTINCT FROM (NEW."url_name") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."parent_id" IS DISTINCT FROM (NEW."parent_id") OR OLD."urn" IS DISTINCT FROM (NEW."urn") OR OLD."html_type" IS DISTINCT FROM (NEW."html_type"))', func='INSERT INTO "users_menushistory" ("id", "created", "modified", "organization_id", "is_removed", "tree_id", "level", "lft", "rght", "display_order", "category", "url_name", "display_name", "infos", "parent_id", "urn", "html_type", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."organization_id", NEW."is_removed", NEW."tree_id", NEW."level", NEW."lft", NEW."rght", NEW."display_order", NEW."category", NEW."url_name", NEW."display_name", NEW."infos", NEW."parent_id", NEW."urn", NEW."html_type", NOW(), \'menu.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='b30e72ecb59473fe098d9f8890e6c22ecdf5cf16', operation='UPDATE', pgid='pgtrigger_menu_snapshot_update_182ff', table='users_menus', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='menuauthgroup',
            trigger=pgtrigger.compiler.Trigger(name='menuauthgroup_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."read" IS DISTINCT FROM (NEW."read") OR OLD."write" IS DISTINCT FROM (NEW."write") OR OLD."auth_group_id" IS DISTINCT FROM (NEW."auth_group_id") OR OLD."menu_id" IS DISTINCT FROM (NEW."menu_id"))', func='INSERT INTO "users_menu_auth_groupshistory" ("id", "created", "modified", "is_removed", "read", "write", "auth_group_id", "menu_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."read", NEW."write", NEW."auth_group_id", NEW."menu_id", NOW(), \'menuauthgroup.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='29113447020422332123c843938f69550cb14787', operation='UPDATE', pgid='pgtrigger_menuauthgroup_snapshot_update_f44f0', table='users_menu_auth_groups', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='permissionproxy',
            trigger=pgtrigger.compiler.Trigger(name='permission_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."content_type_id" IS DISTINCT FROM (NEW."content_type_id") OR OLD."codename" IS DISTINCT FROM (NEW."codename") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "users_permissionshistory" ("name", "content_type_id", "codename", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."name", NEW."content_type_id", NEW."codename", NEW."id", NOW(), \'permission.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='c570520b0d0ce0e203e23acf4bea2dabbee83adf', operation='UPDATE', pgid='pgtrigger_permission_snapshot_update_aba8a', table='auth_permission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='user_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_superuser" IS DISTINCT FROM (NEW."is_superuser") OR OLD."is_staff" IS DISTINCT FROM (NEW."is_staff") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."organization_id" IS DISTINCT FROM (NEW."organization_id") OR OLD."date_joined" IS DISTINCT FROM (NEW."date_joined") OR OLD."username" IS DISTINCT FROM (NEW."username") OR OLD."last_login" IS DISTINCT FROM (NEW."last_login") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."name" IS DISTINCT FROM (NEW."name"))', func='INSERT INTO "users_userhistory" ("id", "is_superuser", "is_staff", "is_active", "organization_id", "date_joined", "username", "last_login", "email", "infos", "name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."is_superuser", NEW."is_staff", NEW."is_active", NEW."organization_id", NEW."date_joined", NEW."username", NEW."last_login", NEW."email", NEW."infos", NEW."name", NOW(), \'user.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='f9d3acd2bca6647efeda1e5267d7a0ea34275de5', operation='UPDATE', pgid='pgtrigger_user_snapshot_update_61c01', table='users_user', when='AFTER')),
        ),
    ]
