# Generated by Django 3.0.2 on 2020-01-11 23:34

from django.db import migrations, models
from uuid import uuid4
import django.utils.timezone
import model_utils.fields

from attendees.persons.models import Utility


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid4, primary_key=True, editable=False, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=models.SET(0), to='whereabouts.Organization')),
                ('category', models.ForeignKey(help_text="subtype: for note it's public/counseling sub-types etc", on_delete=models.SET(0), to='persons.Category')),
                ('display_order', models.SmallIntegerField(blank=False, default=0, null=False)),
                ('content_type', models.ForeignKey(on_delete=models.SET(0), to='contenttypes.ContentType')),
                ('object_id', models.CharField(max_length=36)),
                ('body', models.TextField()),
                ('infos', models.JSONField(blank=True, default=Utility.relationship_infos, help_text='Example: {"owner": "John"}. Please keep {} here even no data', null=True)),
            ],
            options={
                'db_table': 'persons_notes',
                'ordering': ('organization', 'category', 'content_type', 'object_id', 'display_order', '-modified',),
            },
        ),
        migrations.RunSQL(Utility.default_sql('persons_notes')),
        migrations.AddIndex(
            model_name='note',
            index=django.contrib.postgres.indexes.GinIndex(fields=['infos'], name='note_infos_gin'),
        ),
        migrations.CreateModel(
            name='NotesHistory',
            fields=[
                ('pgh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid4, editable=False, serialize=False)),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='persons.note')),
                ('object_id', models.CharField(max_length=36)),
                ('display_order', models.SmallIntegerField(default=0)),
                ('body', models.TextField()),
                ('category', models.ForeignKey(db_constraint=False, help_text="subtype: for note it's public/counseling sub-types etc", on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='persons.category')),
                ('content_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='whereabouts.organization')),
                ('infos', models.JSONField(blank=True, default=Utility.relationship_infos, help_text='Example: {"owner": "John"}. Please keep {} here even no data', null=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'db_table': 'persons_noteshistory',
            },
        ),
    ]
