# Generated by Django 3.0.13 on 2021-05-22 22:07

from attendees.persons.models import Utility
import django.contrib.postgres.indexes
from django.db import migrations, models

import django.utils.timezone
import model_utils.fields
from uuid import uuid4


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_note'),
    ]
    operations = [
        migrations.CreateModel(
            name='Past',
            fields=[
                ('id', models.UUIDField(default=uuid4, primary_key=True, editable=False, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=models.SET(0), to='whereabouts.Organization')),
                ('category', models.ForeignKey(help_text="subtype: for education it's primary/high/college sub-types etc", on_delete=models.SET(0), to='persons.Category')),
                ('display_order', models.SmallIntegerField(db_index=True, default=30000)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('object_id', models.CharField(max_length=36)),
                ('when', models.DateTimeField(blank=True, default=Utility.now_with_timezone, null=True)),
                ('finish', models.DateTimeField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('infos', models.JSONField(blank=True, default=Utility.relationship_infos, help_text=('Example: {"show_secret": {"attendee1id": true, "attendee2id": false}}.Please keep {} here even no data',), null=True)),
            ],
            options={
                'db_table': 'persons_pasts',
                'ordering': ('organization', 'category__type', 'display_order', 'category__display_order', 'when'),
            },
            bases=(models.Model, Utility),
        ),
        migrations.RunSQL(Utility.default_sql('persons_pasts')),
        migrations.AddIndex(
            model_name='past',
            index=django.contrib.postgres.indexes.GinIndex(fields=['infos'], name='past_infos_gin'),
        ),
        migrations.CreateModel(
            name='PastsHistory',
            fields=[
                ('pgh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='history', to='persons.past')),
                ('id', models.UUIDField(db_index=True, default=uuid4, editable=False, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('object_id', models.CharField(max_length=36)),
                ('display_order', models.SmallIntegerField(default=30000)),
                ('infos', models.JSONField(blank=True, default=Utility.relationship_infos, help_text=('Example: {"show_secret": {"attendee1id": true, "attendee2id": false}}.Please keep {} here even no data',), null=True)),
                ('category', models.ForeignKey(db_constraint=False, help_text="subtype: for education it's primary/high/college sub-types etc", on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='persons.category')),
                ('content_type', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='whereabouts.organization')),
                ('when', models.DateTimeField(blank=True, default=Utility.now_with_timezone, null=True)),
                ('finish', models.DateTimeField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'db_table': 'persons_pastshistory',
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('persons_pastshistory', original_model_table='persons_pasts')),
    ]

