# Generated by Django 3.0.5 on 2020-05-02 15:48

from uuid import uuid4
from attendees.persons.models import Utility
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folk',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('division', models.ForeignKey(default=0, blank=False, null=False, on_delete=models.SET(0), to='whereabouts.Division')),
                ('category', models.ForeignKey(help_text='subtype: for folk, 0 is family and 25 is other', default=0, on_delete=models.SET(0), to='persons.Category')),
                ('display_order', models.SmallIntegerField(db_index=True, default=0)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('infos', models.JSONField(blank=True, default=dict, help_text='Example: {"2010id": "3"}. Please keep {} here even no data', null=True)),
            ],
            options={
                'db_table': 'persons_folks',
                'ordering': ('division', 'category', 'display_order', '-modified'),
            },
        ),
        migrations.RunSQL(Utility.default_sql('persons_folks')),
        migrations.AddIndex(
            model_name='folk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['infos'], name='folk_infos_gin'),
        ),
    ]
