# Generated by Django 3.0.5 on 2020-05-02 15:48

from uuid import uuid4
from attendees.persons.models import Utility
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folk',
            fields=[
                ('id', models.UUIDField(default=uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('division', models.ForeignKey(default=0, blank=False, null=False, on_delete=models.SET(0), to='whereabouts.Division')),
                ('category', models.ForeignKey(help_text='subtype: for folk, 0 is family and 25 is other', default=0, on_delete=models.SET(0), to='persons.Category')),
                ('display_order', models.SmallIntegerField(db_index=True, default=0)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('infos', models.JSONField(blank=True, default=Utility.folk_infos, help_text='Example: {"print_directory": False}. Please keep {} here even no data', null=True)),
            ],
            options={
                'db_table': 'persons_folks',
                'ordering': ('division', 'category', 'display_order', '-modified'),
            },
        ),
        migrations.RunSQL(Utility.default_sql('persons_folks')),
        migrations.AddIndex(
            model_name='folk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['infos'], name='folk_infos_gin'),
        ),
        migrations.CreateModel(
            name='FolksHistory',
            fields=[
                ('pgh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='history', to='persons.folk')),
                ('id', models.UUIDField(db_index=True, default=uuid4, editable=False, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('division', models.ForeignKey(db_constraint=False, default=0, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='whereabouts.division')),
                ('is_removed', models.BooleanField(default=False)),
                ('display_order', models.SmallIntegerField(default=0)),
                ('infos', models.JSONField(blank=True, default=Utility.folk_infos, help_text='Example: {"print_directory": False}. Please keep {} here even no data', null=True)),
                ('category', models.ForeignKey(db_constraint=False, default=0, help_text='subtype: for folk, 0 is family and 25 is other', on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='persons.category')),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'db_table': 'persons_folkshistory',
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('persons_folkshistory', original_model_table='persons_folks')),
    ]
