# Generated by Django 3.0.2 on 2020-01-13 02:58
from uuid import uuid4

from django.conf import settings
from django.db import migrations, models
from private_storage.fields import PrivateFileField
from private_storage.storage.files import PrivateFileSystemStorage
import django.utils.timezone
import model_utils.fields
import partial_date.fields
from attendees.persons.models.enum import GenderEnum
from attendees.persons.models import Utility


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_folk'),
        ('whereabouts', '0004_division'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pghistory', '0003_auto_20201023_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.UUIDField(default=uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('division', models.ForeignKey(default=0, blank=False, null=False, on_delete=models.SET(0), to='whereabouts.Division')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('first_name2', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('last_name2', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('gender', models.CharField(choices=GenderEnum.choices(), default=GenderEnum.UNSPECIFIED, max_length=11)),
                ('photo', PrivateFileField(blank=True, null=True, storage=PrivateFileSystemStorage(), upload_to='attendee_portrait', verbose_name='Photo')),
                ('actual_birthday', models.DateField(blank=True, null=True)),
                ('estimated_birthday', partial_date.fields.PartialDateField(blank=True, null=True, help_text='1998, 1998-12 or 1992-12-31, please enter 1800 if year not known')),
                ('deathday', models.DateField(blank=True, null=True)),
                # ('progressions', models.JSONField(blank=True, default=dict, help_text='Example: {"Christian": true, "baptized": {"time": "12/31/2020", "place":"SF"}}. Please keep {} here even no data', null=True)),
                ('infos', models.JSONField(blank=True, default=Utility.attendee_infos, help_text=('Example: {"fixed": {"food_pref": "peanut allergy", "nick_name": "John"}}.Please keep {} here even no data'), null=True)),
            ],
            options={
                'db_table': 'persons_attendees',
                'ordering': ['last_name', 'first_name'],
            },
            bases=(Utility, models.Model),
        ),
        migrations.RunSQL(Utility.default_sql('persons_attendees')),
        # migrations.RunSQL(
        #     sql="""
        #         ALTER TABLE persons_attendees DROP COLUMN full_name;
        #         ALTER TABLE persons_attendees ADD COLUMN full_name VARCHAR(70)
        #               GENERATED ALWAYS AS (TRIM(
        #                 COALESCE(first_name, '') || ' ' ||
        #                 COALESCE(last_name, '')  || ' ' ||
        #                 COALESCE(last_name2, '')   ||
        #                 COALESCE(first_name2, '')
        #               )) STORED;
        #         CREATE INDEX attendee_full_name_raw
        #           ON persons_attendees (full_name);
        #         """,
        #     # reverse_sql="",
        # ),  # switching to use opencc for language conversion in Attendee.save()
        migrations.AddIndex(
            model_name='attendee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['infos'], name='attendee_infos_gin'),
        ),
        # migrations.AddIndex(
        #     model_name='attendee',
        #     index=django.contrib.postgres.indexes.GinIndex(fields=['progressions'], name='attendee_progressions_gin'),
        # ),

        migrations.CreateModel(
            name='AttendeesHistory',
            fields=[
                ('pgh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='persons.attendee')),
                ('id', models.UUIDField(default=uuid4, editable=False, serialize=False)),
                ('division', models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='whereabouts.division')),
                ('gender', models.CharField(choices=GenderEnum.choices(), default=GenderEnum['UNSPECIFIED'], max_length=11)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('first_name2', models.CharField(blank=True, max_length=12, null=True)),
                ('last_name2', models.CharField(blank=True, max_length=8, null=True)),
                ('photo', PrivateFileField(blank=True, null=True, storage=PrivateFileSystemStorage(), upload_to='attendee_portrait', verbose_name='Photo')),
                ('actual_birthday', models.DateField(blank=True, null=True)),
                ('estimated_birthday', partial_date.fields.PartialDateField(blank=True, help_text='1998, 1998-12 or 1992-12-31, please enter 1800 if year not known', null=True)),
                ('deathday', models.DateField(blank=True, null=True)),
                ('infos', models.JSONField(blank=True, default=Utility.attendee_infos, help_text='Example: {"fixed": {"food_pref": "peanut allergy", "nick_name": "John"}}.Please keep {} here even no data', null=True)),
            ],
            options={
                'db_table': 'persons_attendeeshistory',
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('persons_attendeeshistory')),
    ]
