# Generated by Django 3.0.2 on 2020-01-13 02:58
from uuid import uuid4
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models
from private_storage.fields import PrivateFileField
from private_storage.storage.files import PrivateFileSystemStorage
import django.utils.timezone
import model_utils.fields
# import partial_date.fields
from partial_date.fields import PartialDateField
from attendees.persons.models.enum import GenderEnum
from attendees.persons.models import Utility


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_folk'),
        ('whereabouts', '0004_division'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pghistory', '0004_auto_20220906_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.UUIDField(default=uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('division', models.ForeignKey(default=0, blank=False, null=False, on_delete=models.SET(0), to='whereabouts.Division')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('first_name2', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('last_name2', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('gender', models.CharField(choices=GenderEnum.choices(), default=GenderEnum.UNSPECIFIED, max_length=11)),
                ('photo', PrivateFileField(blank=True, null=True, storage=PrivateFileSystemStorage(), upload_to='attendee_portrait', verbose_name='Photo')),
                ('actual_birthday', models.DateField(blank=True, null=True)),
                ('estimated_birthday', PartialDateField(blank=True, null=True, help_text='1998, 1998-12 or 1992-12-31, please enter 1800 if year not known')),
                ('deathday', models.DateField(blank=True, null=True)),
                # ('progressions', models.JSONField(blank=True, default=dict, help_text='Example: {"Christian": true, "baptized": {"time": "12/31/2020", "place":"SF"}}. Please keep {} here even no data', null=True)),
                ('infos', models.JSONField(blank=True, default=Utility.attendee_infos, help_text=('Example: {"fixed": {"food_pref": "peanut allergy", "nick_name": "John"}}.Please keep {} here even no data'), null=True)),
            ],
            options={
                'db_table': 'persons_attendees',
                'ordering': ['last_name', 'first_name'],
            },
            bases=(Utility, models.Model),
        ),
        migrations.RunSQL(Utility.default_sql('persons_attendees')),
        # migrations.RunSQL(
        #     sql="""
        #         ALTER TABLE persons_attendees DROP COLUMN full_name;
        #         ALTER TABLE persons_attendees ADD COLUMN full_name VARCHAR(70)
        #               GENERATED ALWAYS AS (TRIM(
        #                 COALESCE(first_name, '') || ' ' ||
        #                 COALESCE(last_name, '')  || ' ' ||
        #                 COALESCE(last_name2, '')   ||
        #                 COALESCE(first_name2, '')
        #               )) STORED;
        #         CREATE INDEX attendee_full_name_raw
        #           ON persons_attendees (full_name);
        #         """,
        #     # reverse_sql="",
        # ),  # switching to use opencc for language conversion in Attendee.save()
        migrations.AddIndex(
            model_name='attendee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['infos'], name='attendee_infos_gin'),
        ),

        migrations.CreateModel(
            name='AttendeesHistory',
            fields=[
                ('pgh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='persons.attendee')),
                ('id', models.UUIDField(db_index=True, default=uuid4, editable=False, serialize=False)),
                ('division', models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='whereabouts.division')),
                ('gender', models.CharField(choices=GenderEnum.choices(), default=GenderEnum['UNSPECIFIED'], max_length=11)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('infos', models.JSONField(blank=True, default=Utility.attendee_infos, help_text='Example: {"fixed": {"food_pref": "peanut allergy", "nick_name": "John"}}.Please keep {} here even no data', null=True)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('first_name2', models.CharField(blank=True, max_length=12, null=True)),
                ('last_name2', models.CharField(blank=True, max_length=8, null=True)),
                ('photo', PrivateFileField(blank=True, null=True, storage=PrivateFileSystemStorage(), upload_to='attendee_portrait', verbose_name='Photo')),
                ('actual_birthday', models.DateField(blank=True, null=True)),
                ('estimated_birthday', PartialDateField(blank=True, help_text='1998, 1998-12 or 1992-12-31, please enter 1800 if year not known', null=True)),
                ('deathday', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persons_attendeeshistory',
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('persons_attendeeshistory')),
        pgtrigger.migrations.AddTrigger(
            model_name='attendee',
            trigger=pgtrigger.compiler.Trigger(name='attendee_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "persons_attendeeshistory" ("created", "modified", "is_removed", "id", "division_id", "gender", "user_id", "infos", "first_name", "last_name", "first_name2", "last_name2", "photo", "actual_birthday", "estimated_birthday", "deathday", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."created", NEW."modified", NEW."is_removed", NEW."id", NEW."division_id", NEW."gender", NEW."user_id", NEW."infos", NEW."first_name", NEW."last_name", NEW."first_name2", NEW."last_name2", NEW."photo", NEW."actual_birthday", NEW."estimated_birthday", NEW."deathday", NOW(), \'attendee.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='5a8a2ae839d5139f323795d1e5274a1b9d4a910d', operation='INSERT', pgid='pgtrigger_attendee_snapshot_insert_7e147', table='persons_attendees', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attendee',
            trigger=pgtrigger.compiler.Trigger(name='attendee_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created" IS DISTINCT FROM NEW."created" OR OLD."modified" IS DISTINCT FROM NEW."modified" OR OLD."is_removed" IS DISTINCT FROM NEW."is_removed" OR OLD."id" IS DISTINCT FROM NEW."id" OR OLD."division_id" IS DISTINCT FROM NEW."division_id" OR OLD."gender" IS DISTINCT FROM NEW."gender" OR OLD."user_id" IS DISTINCT FROM NEW."user_id" OR OLD."infos" IS DISTINCT FROM NEW."infos" OR OLD."first_name" IS DISTINCT FROM NEW."first_name" OR OLD."last_name" IS DISTINCT FROM NEW."last_name" OR OLD."first_name2" IS DISTINCT FROM NEW."first_name2" OR OLD."last_name2" IS DISTINCT FROM NEW."last_name2" OR OLD."photo" IS DISTINCT FROM NEW."photo" OR OLD."actual_birthday" IS DISTINCT FROM NEW."actual_birthday" OR OLD."estimated_birthday" IS DISTINCT FROM NEW."estimated_birthday" OR OLD."deathday" IS DISTINCT FROM NEW."deathday")', func='INSERT INTO "persons_attendeeshistory" ("created", "modified", "is_removed", "id", "division_id", "gender", "user_id", "infos", "first_name", "last_name", "first_name2", "last_name2", "photo", "actual_birthday", "estimated_birthday", "deathday", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."created", NEW."modified", NEW."is_removed", NEW."id", NEW."division_id", NEW."gender", NEW."user_id", NEW."infos", NEW."first_name", NEW."last_name", NEW."first_name2", NEW."last_name2", NEW."photo", NEW."actual_birthday", NEW."estimated_birthday", NEW."deathday", NOW(), \'attendee.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='b52172d1cb997e0ad7cbd9043569d60eb46beb82', operation='UPDATE', pgid='pgtrigger_attendee_snapshot_update_4d7be', table='persons_attendees', when='AFTER')),
        ),
    ]
