# Generated by Django 3.0.2 on 2020-01-21 05:33

from attendees.persons.models import Utility
from django.db import migrations, models

import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0003_price'),
        ('persons', '0008_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(null=False, blank=False, on_delete=models.CASCADE, to='persons.Attendee', related_name="attendings")),
                ('registration', models.ForeignKey(null=True, blank=True, on_delete=models.deletion.SET_NULL, to='persons.Registration')),
                ('category', models.CharField(max_length=20, null=False, blank=False, default="normal", help_text="normal, not_going, coworker, etc")),
                ('infos', models.JSONField(blank=True, default=dict, help_text='Example: {"grade": 5, "age": 11, "bed_needs": 1, "mobility": 300}. Please keep {} here even no data', null=True)),
                ('price', models.ForeignKey(null=True, blank=True, on_delete=models.deletion.SET_NULL, to='occasions.Price')),
            ],
            options={
                'db_table': 'persons_attendings',
                'ordering': ['registration'],
            },
            bases=(models.Model, Utility),
        ),
        migrations.RunSQL(Utility.default_sql('persons_attendings')),
        migrations.AddConstraint(
            model_name='attending',
            constraint=models.UniqueConstraint(fields=('attendee', 'registration'), condition=models.Q(is_removed=False), name='attending_attendee_registration'),
        ),
        migrations.AddIndex(
            model_name='attending',
            index=django.contrib.postgres.indexes.GinIndex(fields=['infos'], name='attending_infos_gin'),
        ),
        migrations.CreateModel(
            name='AttendingsHistory',
            fields=[
                ('pgh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='history', to='persons.attending')),
                ('id', models.BigIntegerField(db_index=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='persons.attendee')),
                ('infos', models.JSONField(blank=True, default=dict, help_text='Example: {"grade": 5, "age": 11, "bed_needs": 1, "mobility": 300}. Please keep {} here even no data', null=True)),
                ('category', models.CharField(default='normal', help_text='normal, not_going, coworker, etc', max_length=20)),
                ('price', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='occasions.price')),
                ('registration', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='persons.registration')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'db_table': 'persons_attendingshistory',
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('persons_attendingshistory', original_model_table='persons_attendings')),
    ]
