# Generated by Django 3.0.2 on 2020-01-21 05:53

from attendees.persons.models import Utility
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0007_team'),
        ('persons', '0009_attending'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendingMeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('attending', models.ForeignKey(on_delete=models.SET(0), to='persons.Attending')),
                ('meet', models.ForeignKey(on_delete=models.SET(0), to='occasions.Meet')),
                ('start', models.DateTimeField(blank=False, null=False, db_index=True, default=Utility.now_with_timezone)),
                ('finish', models.DateTimeField(blank=False, null=False, db_index=True, help_text="Required for user to filter by time")),
                ('character', models.ForeignKey(on_delete=models.SET(0), to='occasions.Character')),
                ('team', models.ForeignKey(blank=True, default=None, help_text='empty for main meet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occasions.Team')),
                ('category', models.CharField(max_length=20, default='primary', blank=False, null=False, help_text='primary, secondary, etc (primary will be displayed first)')),
                ('infos', models.JSONField(blank=True, default=dict, help_text='Example: {"kid_points": 5, "pdf_folks": ["uuid1"]}. Please keep {} here even no data', null=True)),
            ],
            options={
                'db_table': 'persons_attending_meets',
            },
            bases=(models.Model, Utility),
        ),
        migrations.RunSQL(Utility.default_sql('persons_attending_meets')),
        migrations.AddField(
            model_name='attending',
            name='meets',
            field=models.ManyToManyField(through='persons.AttendingMeet', to='occasions.Meet', related_name="meets"),
        ),
        migrations.AddConstraint(
            model_name='attendingmeet',
            constraint=models.UniqueConstraint(fields=('attending', 'meet'), condition=models.Q(is_removed=False), name='attending_meet'),
        ),
        migrations.AddIndex(
            model_name='attendingmeet',
            index=django.contrib.postgres.indexes.GinIndex(fields=['infos'], name='attendingmeet_infos_gin'),
        ),
        migrations.CreateModel(
            name='AttendingMeetsHistory',
            fields=[
                ('pgh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='history', to='persons.attendingmeet')),
                ('id', models.BigIntegerField()),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('start', models.DateTimeField(default=Utility.now_with_timezone)),
                ('finish', models.DateTimeField(help_text='Required for user to filter by time')),
                ('infos', models.JSONField(blank=True, default=dict, help_text='Example: {"kid_points": 5, "pdf_folks": ["uuid1"]}. Please keep {} here even no data', null=True)),
                ('meet', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='occasions.meet')),
                ('attending', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='persons.attending')),
                ('character', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='occasions.character')),
                ('category', models.CharField(default='primary', help_text='primary, secondary, etc (primary will be displayed first)', max_length=20)),
                ('team', models.ForeignKey(blank=True, db_constraint=False, default=None, help_text='empty for main meet', null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='occasions.team')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'db_table': 'persons_attending_meetshistory',
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('persons_attending_meetshistory', original_model_table='persons_attending_meets')),
    ]
