# Generated by Django 4.2.13 on 2026-06-12 05:17

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0013_folk_attendee_m2m'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='attendee',
            name='attendee_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attending',
            name='attending_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attendingmeet',
            name='attendingmeet_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='category',
            name='category_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='folk',
            name='folk_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='folkattendee',
            name='folkattendee_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='note',
            name='note_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='past',
            name='past_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='registration',
            name='registration_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='relation',
            name='relation_snapshot_update',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attendee',
            trigger=pgtrigger.compiler.Trigger(name='attendee_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."division_id" IS DISTINCT FROM (NEW."division_id") OR OLD."gender" IS DISTINCT FROM (NEW."gender") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."first_name" IS DISTINCT FROM (NEW."first_name") OR OLD."last_name" IS DISTINCT FROM (NEW."last_name") OR OLD."first_name2" IS DISTINCT FROM (NEW."first_name2") OR OLD."last_name2" IS DISTINCT FROM (NEW."last_name2") OR OLD."photo" IS DISTINCT FROM (NEW."photo") OR OLD."actual_birthday" IS DISTINCT FROM (NEW."actual_birthday") OR OLD."estimated_birthday" IS DISTINCT FROM (NEW."estimated_birthday") OR OLD."deathday" IS DISTINCT FROM (NEW."deathday"))', func='INSERT INTO "persons_attendeeshistory" ("created", "modified", "is_removed", "id", "division_id", "gender", "user_id", "infos", "first_name", "last_name", "first_name2", "last_name2", "photo", "actual_birthday", "estimated_birthday", "deathday", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."created", NEW."modified", NEW."is_removed", NEW."id", NEW."division_id", NEW."gender", NEW."user_id", NEW."infos", NEW."first_name", NEW."last_name", NEW."first_name2", NEW."last_name2", NEW."photo", NEW."actual_birthday", NEW."estimated_birthday", NEW."deathday", NOW(), \'attendee.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='7932b5fc41e18b829cc48711b00231a2696757ae', operation='UPDATE', pgid='pgtrigger_attendee_snapshot_update_4d7be', table='persons_attendees', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attending',
            trigger=pgtrigger.compiler.Trigger(name='attending_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."attendee_id" IS DISTINCT FROM (NEW."attendee_id") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."category" IS DISTINCT FROM (NEW."category") OR OLD."price_id" IS DISTINCT FROM (NEW."price_id") OR OLD."registration_id" IS DISTINCT FROM (NEW."registration_id"))', func='INSERT INTO "persons_attendingshistory" ("id", "created", "modified", "is_removed", "attendee_id", "infos", "category", "price_id", "registration_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."attendee_id", NEW."infos", NEW."category", NEW."price_id", NEW."registration_id", NOW(), \'attending.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='3b51dc33a3b4614bcc9438274a017fbc52904c6b', operation='UPDATE', pgid='pgtrigger_attending_snapshot_update_c98f6', table='persons_attendings', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attendingmeet',
            trigger=pgtrigger.compiler.Trigger(name='attendingmeet_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."start" IS DISTINCT FROM (NEW."start") OR OLD."finish" IS DISTINCT FROM (NEW."finish") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."meet_id" IS DISTINCT FROM (NEW."meet_id") OR OLD."attending_id" IS DISTINCT FROM (NEW."attending_id") OR OLD."character_id" IS DISTINCT FROM (NEW."character_id") OR OLD."category_id" IS DISTINCT FROM (NEW."category_id") OR OLD."team_id" IS DISTINCT FROM (NEW."team_id"))', func='INSERT INTO "persons_attending_meetshistory" ("id", "created", "modified", "is_removed", "start", "finish", "infos", "meet_id", "attending_id", "character_id", "category_id", "team_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."start", NEW."finish", NEW."infos", NEW."meet_id", NEW."attending_id", NEW."character_id", NEW."category_id", NEW."team_id", NOW(), \'attendingmeet.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='c8ad0657f7fab727dbc1bb7ebbd17ee85b1322a8', operation='UPDATE', pgid='pgtrigger_attendingmeet_snapshot_update_2082d', table='persons_attending_meets', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='category',
            trigger=pgtrigger.compiler.Trigger(name='category_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."display_order" IS DISTINCT FROM (NEW."display_order") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."type" IS DISTINCT FROM (NEW."type") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name"))', func='INSERT INTO "persons_categorieshistory" ("created", "modified", "is_removed", "id", "display_order", "infos", "type", "display_name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."created", NEW."modified", NEW."is_removed", NEW."id", NEW."display_order", NEW."infos", NEW."type", NEW."display_name", NOW(), \'category.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='999359dcbdd22f8b96514ff7586339f2e222b640', operation='UPDATE', pgid='pgtrigger_category_snapshot_update_d9211', table='persons_categories', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='folk',
            trigger=pgtrigger.compiler.Trigger(name='folk_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."division_id" IS DISTINCT FROM (NEW."division_id") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."display_order" IS DISTINCT FROM (NEW."display_order") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."category_id" IS DISTINCT FROM (NEW."category_id") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name"))', func='INSERT INTO "persons_folkshistory" ("id", "created", "modified", "division_id", "is_removed", "display_order", "infos", "category_id", "display_name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."division_id", NEW."is_removed", NEW."display_order", NEW."infos", NEW."category_id", NEW."display_name", NOW(), \'folk.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='7d47ee09e8870588e8e99b30c06278da3bc47b31', operation='UPDATE', pgid='pgtrigger_folk_snapshot_update_5fd2b', table='persons_folks', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='folkattendee',
            trigger=pgtrigger.compiler.Trigger(name='folkattendee_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."display_order" IS DISTINCT FROM (NEW."display_order") OR OLD."folk_id" IS DISTINCT FROM (NEW."folk_id") OR OLD."attendee_id" IS DISTINCT FROM (NEW."attendee_id") OR OLD."role_id" IS DISTINCT FROM (NEW."role_id") OR OLD."file" IS DISTINCT FROM (NEW."file") OR OLD."start" IS DISTINCT FROM (NEW."start") OR OLD."finish" IS DISTINCT FROM (NEW."finish") OR OLD."infos" IS DISTINCT FROM (NEW."infos"))', func='INSERT INTO "persons_folk_attendeeshistory" ("id", "created", "modified", "is_removed", "display_order", "folk_id", "attendee_id", "role_id", "file", "start", "finish", "infos", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."display_order", NEW."folk_id", NEW."attendee_id", NEW."role_id", NEW."file", NEW."start", NEW."finish", NEW."infos", NOW(), \'folkattendee.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='8ac79ba706f3e74025fe11eb19684d2949e46751', operation='UPDATE', pgid='pgtrigger_folkattendee_snapshot_update_38722', table='persons_folk_attendees', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='note_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."object_id" IS DISTINCT FROM (NEW."object_id") OR OLD."display_order" IS DISTINCT FROM (NEW."display_order") OR OLD."body" IS DISTINCT FROM (NEW."body") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."category_id" IS DISTINCT FROM (NEW."category_id") OR OLD."content_type_id" IS DISTINCT FROM (NEW."content_type_id") OR OLD."organization_id" IS DISTINCT FROM (NEW."organization_id"))', func='INSERT INTO "persons_noteshistory" ("created", "modified", "is_removed", "id", "object_id", "display_order", "body", "infos", "category_id", "content_type_id", "organization_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."created", NEW."modified", NEW."is_removed", NEW."id", NEW."object_id", NEW."display_order", NEW."body", NEW."infos", NEW."category_id", NEW."content_type_id", NEW."organization_id", NOW(), \'note.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='a734c9a9aed44eaf1e44590e2a1452b6cbe0bb03', operation='UPDATE', pgid='pgtrigger_note_snapshot_update_b2f19', table='persons_notes', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='past',
            trigger=pgtrigger.compiler.Trigger(name='past_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."object_id" IS DISTINCT FROM (NEW."object_id") OR OLD."display_order" IS DISTINCT FROM (NEW."display_order") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."category_id" IS DISTINCT FROM (NEW."category_id") OR OLD."content_type_id" IS DISTINCT FROM (NEW."content_type_id") OR OLD."organization_id" IS DISTINCT FROM (NEW."organization_id") OR OLD."when" IS DISTINCT FROM (NEW."when") OR OLD."finish" IS DISTINCT FROM (NEW."finish") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name"))', func='INSERT INTO "persons_pastshistory" ("created", "modified", "is_removed", "id", "object_id", "display_order", "infos", "category_id", "content_type_id", "organization_id", "when", "finish", "display_name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."created", NEW."modified", NEW."is_removed", NEW."id", NEW."object_id", NEW."display_order", NEW."infos", NEW."category_id", NEW."content_type_id", NEW."organization_id", NEW."when", NEW."finish", NEW."display_name", NOW(), \'past.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='736116add1c779892409db1a47271f8161e93a18', operation='UPDATE', pgid='pgtrigger_past_snapshot_update_9fb1c', table='persons_pasts', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='registration',
            trigger=pgtrigger.compiler.Trigger(name='registration_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."assembly_id" IS DISTINCT FROM (NEW."assembly_id") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."registrant_id" IS DISTINCT FROM (NEW."registrant_id"))', func='INSERT INTO "persons_registrationshistory" ("id", "created", "modified", "is_removed", "assembly_id", "infos", "registrant_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."assembly_id", NEW."infos", NEW."registrant_id", NOW(), \'registration.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='3a9e0dedcd44ba0766558b0d2d5fc6ef22b6af1a', operation='UPDATE', pgid='pgtrigger_registration_snapshot_update_ce443', table='persons_registrations', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='relation',
            trigger=pgtrigger.compiler.Trigger(name='relation_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."display_order" IS DISTINCT FROM (NEW."display_order") OR OLD."emergency_contact" IS DISTINCT FROM (NEW."emergency_contact") OR OLD."scheduler" IS DISTINCT FROM (NEW."scheduler") OR OLD."relative" IS DISTINCT FROM (NEW."relative") OR OLD."consanguinity" IS DISTINCT FROM (NEW."consanguinity") OR OLD."reciprocal_ids" IS DISTINCT FROM (NEW."reciprocal_ids") OR OLD."gender" IS DISTINCT FROM (NEW."gender") OR OLD."title" IS DISTINCT FROM (NEW."title"))', func='INSERT INTO "persons_relationshistory" ("id", "created", "modified", "is_removed", "display_order", "emergency_contact", "scheduler", "relative", "consanguinity", "reciprocal_ids", "gender", "title", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."display_order", NEW."emergency_contact", NEW."scheduler", NEW."relative", NEW."consanguinity", NEW."reciprocal_ids", NEW."gender", NEW."title", NOW(), \'relation.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='9a543711d206bed5179a6680ea55b77980113d64', operation='UPDATE', pgid='pgtrigger_relation_snapshot_update_b9a34', table='persons_relations', when='AFTER')),
        ),
    ]
