# Generated by Django 4.2.30 on 2026-10-09 02:02

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0014_remove_attendee_attendee_snapshot_update_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='attendee',
            name='attendee_snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attendee',
            name='attendee_before_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attendee',
            name='attendee_snapshot_update',
        ),
        migrations.AddField(
            model_name='attendee',
            name='merged_into',
            field=models.ForeignKey(blank=True, default=None, help_text='Set when this attendee was merged into another; the row stays as a tombstone so the old id can still be followed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='persons.attendee'),
        ),
        migrations.AddField(
            model_name='attendeeshistory',
            name='merged_into',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, help_text='Set when this attendee was merged into another; the row stays as a tombstone so the old id can still be followed.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merged_from', to='persons.attendee'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attendee',
            trigger=pgtrigger.compiler.Trigger(name='attendee_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "persons_attendeeshistory" ("merged_into_id", "created", "modified", "is_removed", "id", "division_id", "gender", "user_id", "infos", "first_name", "last_name", "first_name2", "last_name2", "photo", "actual_birthday", "estimated_birthday", "deathday", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."merged_into_id", NEW."created", NEW."modified", NEW."is_removed", NEW."id", NEW."division_id", NEW."gender", NEW."user_id", NEW."infos", NEW."first_name", NEW."last_name", NEW."first_name2", NEW."last_name2", NEW."photo", NEW."actual_birthday", NEW."estimated_birthday", NEW."deathday", NOW(), \'attendee.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='02b69d7b51d34cb345be133faae176c0c81104ff', operation='INSERT', pgid='pgtrigger_attendee_snapshot_insert_7e147', table='persons_attendees', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attendee',
            trigger=pgtrigger.compiler.Trigger(name='attendee_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."merged_into_id" IS DISTINCT FROM (NEW."merged_into_id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."division_id" IS DISTINCT FROM (NEW."division_id") OR OLD."gender" IS DISTINCT FROM (NEW."gender") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."first_name" IS DISTINCT FROM (NEW."first_name") OR OLD."last_name" IS DISTINCT FROM (NEW."last_name") OR OLD."first_name2" IS DISTINCT FROM (NEW."first_name2") OR OLD."last_name2" IS DISTINCT FROM (NEW."last_name2") OR OLD."photo" IS DISTINCT FROM (NEW."photo") OR OLD."actual_birthday" IS DISTINCT FROM (NEW."actual_birthday") OR OLD."estimated_birthday" IS DISTINCT FROM (NEW."estimated_birthday") OR OLD."deathday" IS DISTINCT FROM (NEW."deathday"))', func='INSERT INTO "persons_attendeeshistory" ("merged_into_id", "created", "modified", "is_removed", "id", "division_id", "gender", "user_id", "infos", "first_name", "last_name", "first_name2", "last_name2", "photo", "actual_birthday", "estimated_birthday", "deathday", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."merged_into_id", NEW."created", NEW."modified", NEW."is_removed", NEW."id", NEW."division_id", NEW."gender", NEW."user_id", NEW."infos", NEW."first_name", NEW."last_name", NEW."first_name2", NEW."last_name2", NEW."photo", NEW."actual_birthday", NEW."estimated_birthday", NEW."deathday", NOW(), \'attendee.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='5b29f9ec47a9278a074e997e10a743cba51676c4', operation='UPDATE', pgid='pgtrigger_attendee_snapshot_update_4d7be', table='persons_attendees', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attendee',
            trigger=pgtrigger.compiler.Trigger(name='attendee_before_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "persons_attendeeshistory" ("merged_into_id", "created", "modified", "is_removed", "id", "division_id", "gender", "user_id", "infos", "first_name", "last_name", "first_name2", "last_name2", "photo", "actual_birthday", "estimated_birthday", "deathday", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (OLD."merged_into_id", OLD."created", OLD."modified", OLD."is_removed", OLD."id", OLD."division_id", OLD."gender", OLD."user_id", OLD."infos", OLD."first_name", OLD."last_name", OLD."first_name2", OLD."last_name2", OLD."photo", OLD."actual_birthday", OLD."estimated_birthday", OLD."deathday", NOW(), \'attendee.before_delete\', OLD."id", _pgh_attach_context()); RETURN NULL;', hash='0e4741424d0ffe0cb7d4cb2bb843e844f9c3b096', operation='DELETE', pgid='pgtrigger_attendee_before_delete_c7737', table='persons_attendees', when='AFTER')),
        ),
    ]
