# Generated by Django 3.0.2 on 2020-01-13 05:14

from attendees.persons.models import Utility
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whereabouts', '0002_minimal_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('slug', models.SlugField(help_text='alphanumeric only', max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('infos', models.JSONField(blank=True, default=Utility.organization_infos, help_text='Example: {"hostname": "where the app deployed"}. Please keep {} here even no data', null=True)),
            ],
            options={
                'db_table': 'whereabouts_organizations',
            },
            bases=(models.Model, Utility),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=django.contrib.postgres.indexes.GinIndex(fields=['infos'], name='organization_infos_gin'),
        ),
        migrations.RunSQL(Utility.default_sql('whereabouts_organizations')),
        migrations.CreateModel(
            name='OrganizationsHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='history', to='whereabouts.organization')),
                ('id', models.BigIntegerField()),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('slug', models.SlugField(db_index=False, help_text='alphanumeric only')),
                ('display_name', models.CharField(max_length=50)),
                ('infos', models.JSONField(blank=True, default=Utility.organization_infos, help_text='Example: {"hostname": "where the app deployed"}. Please keep {} here even no data', null=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'db_table': 'whereabouts_organizationshistory',
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('whereabouts_organizationshistory', original_model_table='whereabouts_organizations', index_on_id=True)),
    ]
