# Generated by Django 3.0.2 on 2020-01-13 05:27

from attendees.persons.models import Utility
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whereabouts', '0003_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=models.SET(0), to='whereabouts.Organization')),
                ('audience_auth_group', models.ForeignKey(on_delete=models.SET(0), to='auth.Group', null=False, blank=False, help_text='which auth group does the joining general participant belong to?')),
                ('display_name', models.CharField(max_length=50, help_text='"Junior Ministry" is a magic word to show certain Attendee infos in attendee_update_view.js')),
                ('slug', models.SlugField(max_length=50, unique=True)),
                ('infos', models.JSONField(blank=True, default=dict, help_text='Example: {"show_attendee_infos": {"insurer": true}}. Please keep {} here even no data', null=True)),
            ],
            options={
                'db_table': 'whereabouts_divisions',
            },
            bases=(models.Model, Utility),
        ),
        migrations.RunSQL(Utility.default_sql('whereabouts_divisions')),
        migrations.AddIndex(
            model_name='division',
            index=django.contrib.postgres.indexes.GinIndex(fields=['infos'], name='division_infos_gin'),
        ),
        migrations.CreateModel(
            name='DivisionsHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='history', to='whereabouts.division')),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('organization', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='whereabouts.organization')),
                ('is_removed', models.BooleanField(default=False)),
                ('audience_auth_group', models.ForeignKey(db_constraint=False, help_text='which auth group does the joining general participant belong to?', on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='auth.group')),
                ('infos', models.JSONField(blank=True, default=dict, help_text='Example: {"show_attendee_infos": {"insurer": true}}. Please keep {} here even no data', null=True)),
                ('slug', models.SlugField(db_index=False)),
                ('display_name', models.CharField(help_text='"Junior Ministry" is a magic word to show certain Attendee infos in attendee_update_view.js', max_length=50)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'db_table': 'whereabouts_divisionshistory',
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('whereabouts_divisionshistory', original_model_table='whereabouts_divisions', index_on_id=True)),
    ]
