# Generated by Django 3.0.2 on 2020-01-14 06:22

from attendees.persons.models import Utility
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whereabouts', '0004_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(verbose_name='used by', on_delete=models.SET(0), to='whereabouts.Organization', help_text='which organization use this?')),
                ('display_name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=50, unique=True)),
                ('infos', models.JSONField(blank=True, default=dict, help_text='Example: {"hostname": "where the app deployed"}. Please keep {} here even no data', null=True)),

            ],
            options={
                'db_table': 'whereabouts_campuses',
                'verbose_name_plural': 'Campuses',
            },
            bases=(models.Model, Utility),
        ),
        migrations.RunSQL(Utility.default_sql('whereabouts_campuses')),
        migrations.AddIndex(
            model_name='campus',
            index=django.contrib.postgres.indexes.GinIndex(fields=['infos'], name='campus_infos_gin'),
        ),
        migrations.CreateModel(
            name='CampusesHistory',
            fields=[
                ('pgh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='history', to='whereabouts.campus')),
                ('id', models.BigIntegerField(db_index=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(db_constraint=False, help_text='which organization use this?', on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='whereabouts.organization', verbose_name='used by')),
                ('infos', models.JSONField(blank=True, default=dict, help_text='Example: {"hostname": "where the app deployed"}. Please keep {} here even no data', null=True)),
                ('slug', models.SlugField(db_index=False)),
                ('display_name', models.CharField(max_length=50)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'db_table': 'whereabouts_campuseshistory',
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('whereabouts_campuseshistory', original_model_table='whereabouts_campuses')),

    ]
