# Generated by Django 3.0.2 on 2020-01-14 06:36

from attendees.persons.models import Utility
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whereabouts', '0006_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='whereabouts.Property')),
                ('display_name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=50, unique=True)),
                ('site', models.CharField(blank=True, null=True, help_text='2F floor, etc', max_length=50)),
            ],
            options={
                'db_table': 'whereabouts_suites',
            },
            bases=(models.Model, Utility),
        ),
        migrations.RunSQL(Utility.default_sql('whereabouts_suites')),
        migrations.CreateModel(
            name='SuitesHistory',
            fields=[
                ('pgh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='history', to='whereabouts.suite')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('site', models.CharField(blank=True, null=True, help_text='2F floor, etc', max_length=50)),
                ('id', models.BigIntegerField(db_index=True)),
                ('property', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='whereabouts.property')),
                ('slug', models.SlugField(db_index=False)),
                ('display_name', models.CharField(max_length=50)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'db_table': 'whereabouts_suiteshistory',
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('whereabouts_suiteshistory', original_model_table='whereabouts_suites')),
        pgtrigger.migrations.AddTrigger(
            model_name='suite',
            trigger=pgtrigger.compiler.Trigger(name='suite_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "whereabouts_suiteshistory" ("created", "modified", "is_removed", "site", "id", "property_id", "slug", "display_name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."created", NEW."modified", NEW."is_removed", NEW."site", NEW."id", NEW."property_id", NEW."slug", NEW."display_name", NOW(), \'suite.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='6cca6d2bcd26192ddf71197989d7361066877cec', operation='INSERT', pgid='pgtrigger_suite_snapshot_insert_77d30', table='whereabouts_suites', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='suite',
            trigger=pgtrigger.compiler.Trigger(name='suite_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created" IS DISTINCT FROM NEW."created" OR OLD."modified" IS DISTINCT FROM NEW."modified" OR OLD."is_removed" IS DISTINCT FROM NEW."is_removed" OR OLD."site" IS DISTINCT FROM NEW."site" OR OLD."id" IS DISTINCT FROM NEW."id" OR OLD."property_id" IS DISTINCT FROM NEW."property_id" OR OLD."slug" IS DISTINCT FROM NEW."slug" OR OLD."display_name" IS DISTINCT FROM NEW."display_name")', func='INSERT INTO "whereabouts_suiteshistory" ("created", "modified", "is_removed", "site", "id", "property_id", "slug", "display_name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."created", NEW."modified", NEW."is_removed", NEW."site", NEW."id", NEW."property_id", NEW."slug", NEW."display_name", NOW(), \'suite.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='5f6d5b8cfec34a1fe093e358fd8c255d05d4fb55', operation='UPDATE', pgid='pgtrigger_suite_snapshot_update_4094a', table='whereabouts_suites', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='suite',
            trigger=pgtrigger.compiler.Trigger(name='suite_before_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "whereabouts_suiteshistory" ("created", "modified", "is_removed", "site", "id", "property_id", "slug", "display_name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (OLD."created", OLD."modified", OLD."is_removed", OLD."site", OLD."id", OLD."property_id", OLD."slug", OLD."display_name", NOW(), \'suite.before_delete\', OLD."id", _pgh_attach_context()); RETURN NULL;', hash='0909c2f1a85490d00cbffe25f67b2dea553804e7', operation='DELETE', pgid='pgtrigger_suite_before_delete_7e51c', table='whereabouts_suites', when='AFTER')),
        ),
    ]
