# Generated by Django 3.0.2 on 2020-01-14 06:36

from attendees.persons.models import Utility
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whereabouts', '0007_suite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('suite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='whereabouts.Suite')),
                ('display_name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=50, unique=True)),
                ('label', models.CharField(blank=True, max_length=20)),
                ('infos', models.JSONField(blank=True, default=dict, help_text='Example: {"accessibility": 3}. Please keep {} here even no data', null=True)),
            ],
            options={
                'db_table': 'whereabouts_rooms',
            },
            bases=(models.Model, Utility),
        ),
        migrations.RunSQL(Utility.default_sql('whereabouts_rooms')),
        migrations.AddIndex(
            model_name='room',
            index=django.contrib.postgres.indexes.GinIndex(fields=['infos'], name='room_infos_gin'),
        ),
    ]
