# Generated by Django 3.2.11 on 2022-04-11 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0003_auto_20201023_1636'),
        ('address', '0005_address_extra'),
        ('whereabouts', '0009_add_fields_to_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='address.country')),
                ('id', models.IntegerField()),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('code', models.CharField(blank=True, max_length=2)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
