# Generated by Django 3.2.11 on 2022-04-11 18:44

from django.db import migrations, models
import django.db.models.deletion

from attendees.persons.models import Utility


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_address_extra'),
        ('pghistory', '0003_auto_20201023_1636'),
        ('whereabouts', '0011_state_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='address.locality')),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('state', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='address.state')),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(blank=True, max_length=165)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('whereabouts_localityhistory', index_on_id=True, original_model_table='address_locality')),
    ]
