# Generated by Django 4.2.13 on 2026-06-12 05:17

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_address_extra'),
        ('whereabouts', '0013_address_history'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='addressproxy',
            name='address_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='campus',
            name='campus_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='countryproxy',
            name='country_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='division',
            name='division_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='localityproxy',
            name='locality_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='organization',
            name='organization_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='place',
            name='place_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='property',
            name='property_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='room',
            name='room_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='stateproxy',
            name='state_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='suite',
            name='suite_snapshot_update',
        ),
        migrations.AlterField(
            model_name='addresshistory',
            name='locality',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='address.locality'),
        ),
        migrations.AlterField(
            model_name='localityhistory',
            name='state',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='localities', to='address.state'),
        ),
        migrations.AlterField(
            model_name='statehistory',
            name='country',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='states', to='address.country'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='addressproxy',
            trigger=pgtrigger.compiler.Trigger(name='address_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."street_number" IS DISTINCT FROM (NEW."street_number") OR OLD."route" IS DISTINCT FROM (NEW."route") OR OLD."extra" IS DISTINCT FROM (NEW."extra") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."type" IS DISTINCT FROM (NEW."type") OR OLD."hash" IS DISTINCT FROM (NEW."hash") OR OLD."locality_id" IS DISTINCT FROM (NEW."locality_id") OR OLD."raw" IS DISTINCT FROM (NEW."raw") OR OLD."formatted" IS DISTINCT FROM (NEW."formatted") OR OLD."latitude" IS DISTINCT FROM (NEW."latitude") OR OLD."longitude" IS DISTINCT FROM (NEW."longitude") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "whereabouts_addresshistory" ("street_number", "route", "extra", "name", "type", "hash", "locality_id", "raw", "formatted", "latitude", "longitude", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."street_number", NEW."route", NEW."extra", NEW."name", NEW."type", NEW."hash", NEW."locality_id", NEW."raw", NEW."formatted", NEW."latitude", NEW."longitude", NEW."id", NOW(), \'address.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='7253fd9bda0edd2f9e384a4464cb28926ca6a916', operation='UPDATE', pgid='pgtrigger_address_snapshot_update_0c833', table='address_address', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='campus',
            trigger=pgtrigger.compiler.Trigger(name='campus_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."organization_id" IS DISTINCT FROM (NEW."organization_id") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."slug" IS DISTINCT FROM (NEW."slug") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name"))', func='INSERT INTO "whereabouts_campuseshistory" ("id", "created", "modified", "is_removed", "organization_id", "infos", "slug", "display_name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."organization_id", NEW."infos", NEW."slug", NEW."display_name", NOW(), \'campus.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='3b08869179fb66991ec4d6e05754bb392a2b1f70', operation='UPDATE', pgid='pgtrigger_campus_snapshot_update_a55d9', table='whereabouts_campuses', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='countryproxy',
            trigger=pgtrigger.compiler.Trigger(name='country_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."code" IS DISTINCT FROM (NEW."code") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "whereabouts_countryhistory" ("name", "code", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."name", NEW."code", NEW."id", NOW(), \'country.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='7b79a2b56a47df327c82950e340bb6f792995d02', operation='UPDATE', pgid='pgtrigger_country_snapshot_update_549a4', table='address_country', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='division',
            trigger=pgtrigger.compiler.Trigger(name='division_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."organization_id" IS DISTINCT FROM (NEW."organization_id") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."audience_auth_group_id" IS DISTINCT FROM (NEW."audience_auth_group_id") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."slug" IS DISTINCT FROM (NEW."slug") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name"))', func='INSERT INTO "whereabouts_divisionshistory" ("id", "created", "modified", "organization_id", "is_removed", "audience_auth_group_id", "infos", "slug", "display_name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."organization_id", NEW."is_removed", NEW."audience_auth_group_id", NEW."infos", NEW."slug", NEW."display_name", NOW(), \'division.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='e86cdde860efdf63a4cabb6829ab44a12e67c61c', operation='UPDATE', pgid='pgtrigger_division_snapshot_update_655b3', table='whereabouts_divisions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='localityproxy',
            trigger=pgtrigger.compiler.Trigger(name='locality_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."postal_code" IS DISTINCT FROM (NEW."postal_code") OR OLD."state_id" IS DISTINCT FROM (NEW."state_id") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "whereabouts_localityhistory" ("name", "postal_code", "state_id", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."name", NEW."postal_code", NEW."state_id", NEW."id", NOW(), \'locality.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='c79b2a0919c9e8b6effc0787dfb120a7c0e77698', operation='UPDATE', pgid='pgtrigger_locality_snapshot_update_0c9dc', table='address_locality', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='organization',
            trigger=pgtrigger.compiler.Trigger(name='organization_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."slug" IS DISTINCT FROM (NEW."slug") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name") OR OLD."infos" IS DISTINCT FROM (NEW."infos"))', func='INSERT INTO "whereabouts_organizationshistory" ("id", "created", "modified", "is_removed", "slug", "display_name", "infos", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."slug", NEW."display_name", NEW."infos", NOW(), \'organization.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='ee4dcf26b9c4e3f8021dc0afa683264f090453bf', operation='UPDATE', pgid='pgtrigger_organization_snapshot_update_f9b6d', table='whereabouts_organizations', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='place',
            trigger=pgtrigger.compiler.Trigger(name='place_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."organization_id" IS DISTINCT FROM (NEW."organization_id") OR OLD."content_type_id" IS DISTINCT FROM (NEW."content_type_id") OR OLD."object_id" IS DISTINCT FROM (NEW."object_id") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."display_order" IS DISTINCT FROM (NEW."display_order") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name") OR OLD."address_id" IS DISTINCT FROM (NEW."address_id") OR OLD."start" IS DISTINCT FROM (NEW."start") OR OLD."finish" IS DISTINCT FROM (NEW."finish"))', func='INSERT INTO "whereabouts_placeshistory" ("created", "id", "modified", "is_removed", "organization_id", "content_type_id", "object_id", "infos", "display_order", "display_name", "address_id", "start", "finish", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."created", NEW."id", NEW."modified", NEW."is_removed", NEW."organization_id", NEW."content_type_id", NEW."object_id", NEW."infos", NEW."display_order", NEW."display_name", NEW."address_id", NEW."start", NEW."finish", NOW(), \'place.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='aca7af3f5c8634c6d5275187e60ce5e5ebbdf975', operation='UPDATE', pgid='pgtrigger_place_snapshot_update_d5a98', table='whereabouts_places', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='property',
            trigger=pgtrigger.compiler.Trigger(name='property_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."campus_id" IS DISTINCT FROM (NEW."campus_id") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."slug" IS DISTINCT FROM (NEW."slug") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name"))', func='INSERT INTO "whereabouts_propertieshistory" ("created", "modified", "is_removed", "id", "campus_id", "infos", "slug", "display_name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."created", NEW."modified", NEW."is_removed", NEW."id", NEW."campus_id", NEW."infos", NEW."slug", NEW."display_name", NOW(), \'property.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='a1e78386c7f6674f048417e0924fec701b441eb2', operation='UPDATE', pgid='pgtrigger_property_snapshot_update_8342b', table='whereabouts_properties', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='room',
            trigger=pgtrigger.compiler.Trigger(name='room_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."slug" IS DISTINCT FROM (NEW."slug") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."suite_id" IS DISTINCT FROM (NEW."suite_id") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name") OR OLD."label" IS DISTINCT FROM (NEW."label"))', func='INSERT INTO "whereabouts_roomshistory" ("created", "modified", "is_removed", "slug", "id", "infos", "suite_id", "display_name", "label", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."created", NEW."modified", NEW."is_removed", NEW."slug", NEW."id", NEW."infos", NEW."suite_id", NEW."display_name", NEW."label", NOW(), \'room.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='65cad296340c79c888e70245ecbffe800e75731a', operation='UPDATE', pgid='pgtrigger_room_snapshot_update_76efb', table='whereabouts_rooms', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stateproxy',
            trigger=pgtrigger.compiler.Trigger(name='state_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."code" IS DISTINCT FROM (NEW."code") OR OLD."country_id" IS DISTINCT FROM (NEW."country_id") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "whereabouts_statehistory" ("name", "code", "country_id", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."name", NEW."code", NEW."country_id", NEW."id", NOW(), \'state.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='abe72c3f2e0c0fff13a0cf073dd099acfe21253f', operation='UPDATE', pgid='pgtrigger_state_snapshot_update_5b5db', table='address_state', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='suite',
            trigger=pgtrigger.compiler.Trigger(name='suite_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."site" IS DISTINCT FROM (NEW."site") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."property_id" IS DISTINCT FROM (NEW."property_id") OR OLD."slug" IS DISTINCT FROM (NEW."slug") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name"))', func='INSERT INTO "whereabouts_suiteshistory" ("created", "modified", "is_removed", "site", "id", "property_id", "slug", "display_name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."created", NEW."modified", NEW."is_removed", NEW."site", NEW."id", NEW."property_id", NEW."slug", NEW."display_name", NOW(), \'suite.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='842342c4dd2eebfac07e166943c5af516f19c8c9', operation='UPDATE', pgid='pgtrigger_suite_snapshot_update_4094a', table='whereabouts_suites', when='AFTER')),
        ),
    ]
