# Generated by Django 3.0.2 on 2020-01-14 04:14

from attendees.persons.models.utility import Utility
from django.core.validators import MinValueValidator
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0002_assembly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=False, null=False)),
                ('finish', models.DateTimeField(blank=False, null=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('assembly', models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, to='occasions.Assembly')),
                ('price_value', models.DecimalField(decimal_places=2, default=999999, max_digits=8, validators=[MinValueValidator(0)])),
                ('price_type', models.CharField(db_index=True, max_length=20, help_text="example: no bed_earlybird")),
                ('display_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'occasions_prices',
            },
            bases=(models.Model, Utility),
        ),
        migrations.RunSQL(Utility.default_sql('occasions_prices')),
        migrations.CreateModel(
            name='PricesHistory',
            fields=[
                ('pgh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='history', to='occasions.price')),
                ('id', models.BigIntegerField(db_index=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('assembly', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='occasions.assembly')),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('price_type', models.CharField(max_length=20, help_text="example: no bed_earlybird")),
                ('price_value', models.DecimalField(decimal_places=2, default=999999, max_digits=8, validators=[MinValueValidator(0)])),
                ('display_name', models.CharField(max_length=50)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'db_table': 'occasions_priceshistory',
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('occasions_priceshistory', original_model_table='occasions_prices')),
    ]
