# Generated by Django 3.0.2 on 2020-01-14 05:01

from attendees.persons.models.utility import Utility
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0003_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('assembly', models.ForeignKey(on_delete=models.SET(0), to='occasions.Assembly')),
                ('display_order', models.SmallIntegerField(blank=False, default=0, null=False)),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=50, unique=True, help_text='format: Assembly_name-Character_name')),
                ('type', models.CharField(db_index=True, default='normal', max_length=50)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'occasions_characters',
                'ordering': ['assembly', 'display_order'],
            },
            bases=(models.Model, Utility),
        ),
        migrations.RunSQL(Utility.default_sql('occasions_characters')),
    ]
