# Generated by Django 3.0.2 on 2020-01-14 05:01

from attendees.persons.models.utility import Utility
from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0003_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('assembly', models.ForeignKey(on_delete=models.SET(0), to='occasions.Assembly')),
                ('display_order', models.SmallIntegerField(blank=False, default=0, null=False)),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=50, unique=True, help_text='format: Assembly_name-Character_name')),
                ('type', models.CharField(db_index=True, default='normal', max_length=50)),
                ('infos', models.JSONField(blank=True, default=dict, help_text='example: {"info": "for distrubuting food"}, please keep {} here even there\'s no data', null=True)),
            ],
            options={
                'db_table': 'occasions_characters',
                'ordering': ['assembly', 'display_order'],
            },
            bases=(models.Model, Utility),
        ),
        migrations.RunSQL(Utility.default_sql('occasions_characters')),
        migrations.AddIndex(
            model_name='Character',
            index=GinIndex(fields=['infos'], name='character_infos_gin'),
        ),
        migrations.CreateModel(
            name='CharactersHistory',
            fields=[
                ('pgh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='history', to='occasions.character')),
                ('id', models.BigIntegerField()),
                ('assembly', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='occasions.assembly')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('infos', models.JSONField(blank=True, default=dict, help_text='example: {"info": "for distrubuting food"}, please keep {} here even there\'s no data', null=True)),
                ('display_order', models.SmallIntegerField(default=0)),
                ('slug', models.SlugField(db_index=False, help_text='format: Assembly_name-Character_name')),
                ('type', models.CharField(default='normal', max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'db_table': 'occasions_charactershistory',
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('occasions_charactershistory', original_model_table='occasions_characters', index_on_id=True)),
    ]
