# Generated by Django 3.0.2 on 2020-01-21 03:21

from attendees.persons.models import Utility
from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schedule', '0012_auto_20191025_1852'),
        ('occasions', '0005_meet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=False, null=False)),
                ('finish', models.DateTimeField(blank=False, null=False, help_text="Required for user to filter by time")),
                ('is_removed', models.BooleanField(default=False)),
                ('site_id', models.CharField(max_length=36, null=False, blank=False, default='0')),
                ('meet', models.ForeignKey(on_delete=models.SET(0), to='occasions.Meet')),
                ('site_type', models.ForeignKey(help_text='site: django_content_type id for table name', on_delete=models.SET(0), to='contenttypes.ContentType')),
                ('display_name', models.CharField(blank=True, null=True, max_length=50, help_text="02/09/2020, etc")),
                ('infos', models.JSONField(blank=True, default=dict, help_text='Example: {"LG_location": "F207", "link": "https://..."}. Please keep {} here even no data', null=True)),
            ],
            options={
                'db_table': 'occasions_gatherings',
                'ordering': ['meet', 'start'],
            },
            bases=(models.Model, Utility),
        ),
        migrations.AddConstraint(
            model_name='gathering',
            constraint=models.UniqueConstraint(fields=('meet_id', 'site_type', 'site_id', 'start'), condition=models.Q(is_removed=False), name='uniq_meet_location_time'),
        ),
        migrations.AddIndex(
            model_name='Gathering',
            index=GinIndex(fields=['infos'], name='gathering_infos_gin'),
        ),
        migrations.RunSQL(Utility.default_sql('occasions_gatherings')),
        migrations.CreateModel(
            name='GatheringsHistory',
            fields=[
                ('pgh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='history', to='occasions.gathering')),
                ('id', models.BigIntegerField()),
                ('meet', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='occasions.meet')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField(help_text='Required for user to filter by time')),
                ('site_type', models.ForeignKey(db_constraint=False, help_text='site: django_content_type id for table name', on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype')),
                ('infos', models.JSONField(blank=True, default=dict, help_text='Example: {"LG_location": "F207", "link": "https://..."}. Please keep {} here even no data', null=True)),
                ('site_id', models.CharField(default='0', max_length=36)),
                ('display_name', models.CharField(blank=True, help_text='02/09/2020, etc', max_length=50, null=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'db_table': 'occasions_gatheringshistory',
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('occasions_gatheringshistory', original_model_table='occasions_gatherings', index_on_id=True)),
    ]
