# Generated by Django 3.0.2 on 2020-01-21 06:13

from attendees.persons.models import Utility
from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models

import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0006_gathering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('display_order', models.SmallIntegerField(blank=False, default=0, null=False)),
                ('site_id', models.CharField(default='0', max_length=36)),
                ('site_type', models.ForeignKey(help_text='site: django_content_type id for table name', on_delete=models.SET(0), to='contenttypes.ContentType')),
                ('meet', models.ForeignKey(on_delete=models.SET(0), to='occasions.Meet')),
                ('slug', models.SlugField(max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('infos', models.JSONField(blank=True, default=dict, help_text='Example: {"link": "https://..."}. Please keep {} here even no data', null=True)),
            ],
            options={
                'db_table': 'occasions_teams',
            },
            bases=(models.Model, Utility),
        ),
        migrations.AddIndex(
            model_name='Team',
            index=GinIndex(fields=['infos'], name='team_infos_gin'),
        ),
        migrations.RunSQL(Utility.default_sql('occasions_teams')),
        migrations.CreateModel(
            name='TeamsHistory',
            fields=[
                ('pgh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='history', to='occasions.team')),
                ('id', models.BigIntegerField()),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('meet', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='occasions.meet')),
                ('display_order', models.SmallIntegerField(default=0)),
                ('site_type', models.ForeignKey(db_constraint=False, help_text='site: django_content_type id for table name', on_delete=models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype')),
                ('infos', models.JSONField(blank=True, default=dict, help_text='Example: {"link": "https://..."}. Please keep {} here even no data', null=True)),
                ('site_id', models.CharField(default='0', max_length=36)),
                ('slug', models.SlugField(db_index=False)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'db_table': 'occasions_teamshistory',
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('occasions_teamshistory', original_model_table='occasions_teams', index_on_id=True)),
    ]
