# Generated by Django 3.2.11 on 2022-04-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0003_auto_20201023_1636'),
        ('schedule', '0014_use_autofields_for_pk'),
        ('occasions', '0009_meet_attending'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=models.deletion.DO_NOTHING, related_name='history', to='schedule.calendar')),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('slug', models.SlugField(db_index=False, max_length=200, verbose_name='slug')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
