# Generated by Django 3.2.11 on 2022-04-09 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from attendees.persons.models import Utility


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0003_auto_20201023_1636'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0014_use_autofields_for_pk'),
        ('occasions', '0009_meet_attending'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='schedule.event')),
                ('id', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(help_text='The end time must be later than the start time.', verbose_name='end')),
                ('calendar', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='schedule.calendar', verbose_name='calendar')),
                ('rule', models.ForeignKey(blank=True, db_constraint=False, help_text="Select '----' for a one time only event.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='schedule.rule', verbose_name='rule')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('end_recurring_period', models.DateTimeField(blank=True, help_text='This date is ignored for one time only events.', null=True, verbose_name='end recurring period')),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('color_event', models.CharField(blank=True, max_length=10, verbose_name='Color event')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('occasions_eventhistory', index_on_id=True)),
    ]
