# Generated by Django 3.2.11 on 2022-04-10 13:04

from django.db import migrations, models
import django.db.models.deletion

from attendees.persons.models import Utility


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0003_auto_20201023_1636'),
        ('occasions', '0010_calendar_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarRelationHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='schedule.calendarrelation')),
                ('id', models.IntegerField()),
                ('calendar', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='schedule.calendar', verbose_name='calendar')),
                ('content_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype')),
                ('object_id', models.IntegerField()),
                ('inheritable', models.BooleanField(default=True, verbose_name='inheritable')),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('distinction', models.CharField(max_length=20, verbose_name='distinction')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('occasions_calendarrelationhistory', original_model_table='schedule_calendarrelation')),
    ]
