# Generated by Django 3.2.11 on 2022-04-09 14:42

from django.db import migrations, models
import django.db.models.deletion

from attendees.persons.models import Utility


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0003_auto_20201023_1636'),
        ('occasions', '0010_event_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRelationHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='schedule.eventrelation')),
                ('id', models.IntegerField()),
                ('content_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype')),
                ('object_id', models.IntegerField()),
                ('event', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='schedule.event', verbose_name='event')),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('distinction', models.CharField(max_length=20, verbose_name='distinction')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('occasions_eventrelationhistory')),
    ]
