# Generated by Django 3.2.11 on 2022-04-10 13:04

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from attendees.persons.models import Utility


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0004_auto_20220906_1625'),
        ('occasions', '0013_calendar_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarRelationProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('schedule.calendarrelation',),
        ),
        migrations.CreateModel(
            name='CalendarRelationHistory',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='schedule.calendarrelation')),
                ('id', models.IntegerField()),
                ('calendar', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='schedule.calendar', verbose_name='calendar')),
                ('content_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype')),
                ('object_id', models.IntegerField()),
                ('inheritable', models.BooleanField(default=True, verbose_name='inheritable')),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('distinction', models.CharField(max_length=20, verbose_name='distinction')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(Utility.pgh_default_sql('occasions_calendarrelationhistory', original_model_table='schedule_calendarrelation')),
        pgtrigger.migrations.AddTrigger(
            model_name='calendarrelationproxy',
            trigger=pgtrigger.compiler.Trigger(name='calendarrelation_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "occasions_calendarrelationhistory" ("calendar_id", "content_type_id", "object_id", "distinction", "inheritable", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."calendar_id", NEW."content_type_id", NEW."object_id", NEW."distinction", NEW."inheritable", NEW."id", NOW(), \'calendarrelation.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='fb28a33b801561a9ae8b3fb5ba7760d24356851c', operation='INSERT', pgid='pgtrigger_calendarrelation_snapshot_insert_2a82a', table='schedule_calendarrelation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calendarrelationproxy',
            trigger=pgtrigger.compiler.Trigger(name='calendarrelation_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."calendar_id" IS DISTINCT FROM NEW."calendar_id" OR OLD."content_type_id" IS DISTINCT FROM NEW."content_type_id" OR OLD."object_id" IS DISTINCT FROM NEW."object_id" OR OLD."distinction" IS DISTINCT FROM NEW."distinction" OR OLD."inheritable" IS DISTINCT FROM NEW."inheritable" OR OLD."id" IS DISTINCT FROM NEW."id")', func='INSERT INTO "occasions_calendarrelationhistory" ("calendar_id", "content_type_id", "object_id", "distinction", "inheritable", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."calendar_id", NEW."content_type_id", NEW."object_id", NEW."distinction", NEW."inheritable", NEW."id", NOW(), \'calendarrelation.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='21d0256aff7933b558655e41afabbf37ce7150a9', operation='UPDATE', pgid='pgtrigger_calendarrelation_snapshot_update_251b7', table='schedule_calendarrelation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calendarrelationproxy',
            trigger=pgtrigger.compiler.Trigger(name='calendarrelation_before_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "occasions_calendarrelationhistory" ("calendar_id", "content_type_id", "object_id", "distinction", "inheritable", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (OLD."calendar_id", OLD."content_type_id", OLD."object_id", OLD."distinction", OLD."inheritable", OLD."id", NOW(), \'calendarrelation.before_delete\', OLD."id", _pgh_attach_context()); RETURN NULL;', hash='b3d832e1978125375ac3297a8d7a2c981a03f99d', operation='DELETE', pgid='pgtrigger_calendarrelation_before_delete_1d3f0', table='schedule_calendarrelation', when='AFTER')),
        ),
        migrations.AlterField(
            model_name='calendarrelationhistory',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='occasions.calendarrelationproxy'),
        ),
    ]
