# Generated by Django 3.2.15 on 2022-09-20 15:55

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0004_auto_20220906_1625'),
        ('schedule', '0014_use_autofields_for_pk'),
        ('occasions', '0017_eventrelation_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('schedule.occurrence',),
        ),
        migrations.CreateModel(
            name='OccurrenceHistory',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(verbose_name='end')),
                ('cancelled', models.BooleanField(default=False, verbose_name='cancelled')),
                ('original_start', models.DateTimeField(verbose_name='original start')),
                ('original_end', models.DateTimeField(verbose_name='original end')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('event', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='schedule.event', verbose_name='event')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='occasions.occurrenceproxy')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='occurrenceproxy',
            trigger=pgtrigger.compiler.Trigger(name='occurrence_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "occasions_occurrencehistory" ("event_id", "title", "description", "start", "end", "cancelled", "original_start", "original_end", "created_on", "updated_on", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."event_id", NEW."title", NEW."description", NEW."start", NEW."end", NEW."cancelled", NEW."original_start", NEW."original_end", NEW."created_on", NEW."updated_on", NEW."id", NOW(), \'occurrence.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='3564eb962839426c19b7d154c2ea51da20fbb695', operation='INSERT', pgid='pgtrigger_occurrence_snapshot_insert_902b5', table='schedule_occurrence', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='occurrenceproxy',
            trigger=pgtrigger.compiler.Trigger(name='occurrence_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."event_id" IS DISTINCT FROM NEW."event_id" OR OLD."title" IS DISTINCT FROM NEW."title" OR OLD."description" IS DISTINCT FROM NEW."description" OR OLD."start" IS DISTINCT FROM NEW."start" OR OLD."end" IS DISTINCT FROM NEW."end" OR OLD."cancelled" IS DISTINCT FROM NEW."cancelled" OR OLD."original_start" IS DISTINCT FROM NEW."original_start" OR OLD."original_end" IS DISTINCT FROM NEW."original_end" OR OLD."created_on" IS DISTINCT FROM NEW."created_on" OR OLD."updated_on" IS DISTINCT FROM NEW."updated_on" OR OLD."id" IS DISTINCT FROM NEW."id")', func='INSERT INTO "occasions_occurrencehistory" ("event_id", "title", "description", "start", "end", "cancelled", "original_start", "original_end", "created_on", "updated_on", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."event_id", NEW."title", NEW."description", NEW."start", NEW."end", NEW."cancelled", NEW."original_start", NEW."original_end", NEW."created_on", NEW."updated_on", NEW."id", NOW(), \'occurrence.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='be23114de463aaf281738a1fe78be714c7536ab6', operation='UPDATE', pgid='pgtrigger_occurrence_snapshot_update_ad4df', table='schedule_occurrence', when='AFTER')),
        ),
    ]
