# Generated by Django 4.2.13 on 2026-06-12 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_celery_beat.validators
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('occasions', '0018_occurrence_history'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='assembly',
            name='assembly_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attendance',
            name='attendance_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='calendarproxy',
            name='calendar_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='calendarrelationproxy',
            name='calendarrelation_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='character',
            name='character_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='crontabscheduleproxy',
            name='crontabschedule_snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='crontabscheduleproxy',
            name='crontabschedule_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='crontabscheduleproxy',
            name='crontabschedule_before_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='eventproxy',
            name='event_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='eventrelationproxy',
            name='eventrelation_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='gathering',
            name='gathering_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='intervalscheduleproxy',
            name='intervalschedule_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='meet',
            name='meet_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='messagetemplate',
            name='messagetemplate_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='occurrenceproxy',
            name='occurrence_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='periodictaskproxy',
            name='periodictask_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='price',
            name='price_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='ruleproxy',
            name='rule_snapshot_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='team',
            name='team_snapshot_update',
        ),
        migrations.AlterField(
            model_name='calendarrelationhistory',
            name='calendar',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.calendar', verbose_name='calendar'),
        ),
        migrations.AlterField(
            model_name='calendarrelationhistory',
            name='content_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='crontabschedulehistory',
            name='day_of_week',
            field=models.CharField(default='*', help_text='Cron Days Of The Week to Run. Use "*" for "all", Sunday is 0 or 7, Monday is 1. (Example: "0,5")', max_length=64, validators=[django_celery_beat.validators.day_of_week_validator], verbose_name='Day(s) Of The Week'),
        ),
        migrations.AlterField(
            model_name='crontabschedulehistory',
            name='month_of_year',
            field=models.CharField(default='*', help_text='Cron Months (1-12) Of The Year to Run. Use "*" for "all". (Example: "1,12")', max_length=64, validators=[django_celery_beat.validators.month_of_year_validator], verbose_name='Month(s) Of The Year'),
        ),
        migrations.AlterField(
            model_name='eventhistory',
            name='calendar',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.calendar', verbose_name='calendar'),
        ),
        migrations.AlterField(
            model_name='eventhistory',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='eventhistory',
            name='rule',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Select '----' for a one time only event.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.rule', verbose_name='rule'),
        ),
        migrations.AlterField(
            model_name='eventrelationhistory',
            name='content_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='eventrelationhistory',
            name='event',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='occurrencehistory',
            name='event',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='periodictaskhistory',
            name='clocked',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Clocked Schedule to run the task on.  Set only one schedule type, leave the others null.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.clockedschedule', verbose_name='Clocked Schedule'),
        ),
        migrations.AlterField(
            model_name='periodictaskhistory',
            name='crontab',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Crontab Schedule to run the task on.  Set only one schedule type, leave the others null.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.crontabschedule', verbose_name='Crontab Schedule'),
        ),
        migrations.AlterField(
            model_name='periodictaskhistory',
            name='interval',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Interval Schedule to run the task on.  Set only one schedule type, leave the others null.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.intervalschedule', verbose_name='Interval Schedule'),
        ),
        migrations.AlterField(
            model_name='periodictaskhistory',
            name='solar',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Solar Schedule to run the task on.  Set only one schedule type, leave the others null.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.solarschedule', verbose_name='Solar Schedule'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assembly',
            trigger=pgtrigger.compiler.Trigger(name='assembly_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."division_id" IS DISTINCT FROM (NEW."division_id") OR OLD."display_order" IS DISTINCT FROM (NEW."display_order") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."slug" IS DISTINCT FROM (NEW."slug") OR OLD."category_id" IS DISTINCT FROM (NEW."category_id") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name") OR OLD."start" IS DISTINCT FROM (NEW."start") OR OLD."finish" IS DISTINCT FROM (NEW."finish"))', func='INSERT INTO "occasions_assemblieshistory" ("id", "created", "modified", "is_removed", "division_id", "display_order", "infos", "slug", "category_id", "display_name", "start", "finish", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."division_id", NEW."display_order", NEW."infos", NEW."slug", NEW."category_id", NEW."display_name", NEW."start", NEW."finish", NOW(), \'assembly.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='374ac111e42dda0f6b38b9b585e06a65ee601fac', operation='UPDATE', pgid='pgtrigger_assembly_snapshot_update_44c79', table='occasions_assemblies', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attendance',
            trigger=pgtrigger.compiler.Trigger(name='attendance_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."display_order" IS DISTINCT FROM (NEW."display_order") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."attending_id" IS DISTINCT FROM (NEW."attending_id") OR OLD."character_id" IS DISTINCT FROM (NEW."character_id") OR OLD."gathering_id" IS DISTINCT FROM (NEW."gathering_id") OR OLD."category_id" IS DISTINCT FROM (NEW."category_id") OR OLD."file" IS DISTINCT FROM (NEW."file") OR OLD."team_id" IS DISTINCT FROM (NEW."team_id") OR OLD."start" IS DISTINCT FROM (NEW."start") OR OLD."finish" IS DISTINCT FROM (NEW."finish"))', func='INSERT INTO "occasions_attendanceshistory" ("id", "created", "modified", "is_removed", "display_order", "infos", "attending_id", "character_id", "gathering_id", "category_id", "file", "team_id", "start", "finish", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."display_order", NEW."infos", NEW."attending_id", NEW."character_id", NEW."gathering_id", NEW."category_id", NEW."file", NEW."team_id", NEW."start", NEW."finish", NOW(), \'attendance.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='0d35af1bfbb7be02d8ecfca74ab19d07b6a0f601', operation='UPDATE', pgid='pgtrigger_attendance_snapshot_update_8e986', table='occasions_attendances', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calendarproxy',
            trigger=pgtrigger.compiler.Trigger(name='calendar_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."slug" IS DISTINCT FROM (NEW."slug") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "occasions_calendarhistory" ("name", "slug", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."name", NEW."slug", NEW."id", NOW(), \'calendar.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='ef7df83c08f7e01029b6803c0958ada44b2d9683', operation='UPDATE', pgid='pgtrigger_calendar_snapshot_update_c7ecc', table='schedule_calendar', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calendarrelationproxy',
            trigger=pgtrigger.compiler.Trigger(name='calendarrelation_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."calendar_id" IS DISTINCT FROM (NEW."calendar_id") OR OLD."content_type_id" IS DISTINCT FROM (NEW."content_type_id") OR OLD."object_id" IS DISTINCT FROM (NEW."object_id") OR OLD."distinction" IS DISTINCT FROM (NEW."distinction") OR OLD."inheritable" IS DISTINCT FROM (NEW."inheritable") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "occasions_calendarrelationhistory" ("calendar_id", "content_type_id", "object_id", "distinction", "inheritable", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."calendar_id", NEW."content_type_id", NEW."object_id", NEW."distinction", NEW."inheritable", NEW."id", NOW(), \'calendarrelation.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='4b7d961c672bda3d04352d5b16c8373cdb965dc1', operation='UPDATE', pgid='pgtrigger_calendarrelation_snapshot_update_251b7', table='schedule_calendarrelation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='character',
            trigger=pgtrigger.compiler.Trigger(name='character_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."assembly_id" IS DISTINCT FROM (NEW."assembly_id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."display_order" IS DISTINCT FROM (NEW."display_order") OR OLD."slug" IS DISTINCT FROM (NEW."slug") OR OLD."type" IS DISTINCT FROM (NEW."type") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name"))', func='INSERT INTO "occasions_charactershistory" ("id", "assembly_id", "created", "modified", "is_removed", "infos", "display_order", "slug", "type", "display_name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."assembly_id", NEW."created", NEW."modified", NEW."is_removed", NEW."infos", NEW."display_order", NEW."slug", NEW."type", NEW."display_name", NOW(), \'character.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='b5095f486a31accb87dbd5cea07eb853e070564a', operation='UPDATE', pgid='pgtrigger_character_snapshot_update_a6f12', table='occasions_characters', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='crontabscheduleproxy',
            trigger=pgtrigger.compiler.Trigger(name='crontabschedule_snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "occasions_crontabschedulehistory" ("minute", "hour", "day_of_month", "month_of_year", "day_of_week", "timezone", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."minute", NEW."hour", NEW."day_of_month", NEW."month_of_year", NEW."day_of_week", NEW."timezone", NEW."id", NOW(), \'crontabschedule.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='5ef1f5743ea4761aedfeeca82b4fa68e953ebc5d', operation='INSERT', pgid='pgtrigger_crontabschedule_snapshot_insert_c7b77', table='django_celery_beat_crontabschedule', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='crontabscheduleproxy',
            trigger=pgtrigger.compiler.Trigger(name='crontabschedule_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."minute" IS DISTINCT FROM (NEW."minute") OR OLD."hour" IS DISTINCT FROM (NEW."hour") OR OLD."day_of_month" IS DISTINCT FROM (NEW."day_of_month") OR OLD."month_of_year" IS DISTINCT FROM (NEW."month_of_year") OR OLD."day_of_week" IS DISTINCT FROM (NEW."day_of_week") OR OLD."timezone" IS DISTINCT FROM (NEW."timezone") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "occasions_crontabschedulehistory" ("minute", "hour", "day_of_month", "month_of_year", "day_of_week", "timezone", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."minute", NEW."hour", NEW."day_of_month", NEW."month_of_year", NEW."day_of_week", NEW."timezone", NEW."id", NOW(), \'crontabschedule.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='636332c9234b3fbf48aa5689c42fc7ce678614e0', operation='UPDATE', pgid='pgtrigger_crontabschedule_snapshot_update_3cf20', table='django_celery_beat_crontabschedule', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='crontabscheduleproxy',
            trigger=pgtrigger.compiler.Trigger(name='crontabschedule_before_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "occasions_crontabschedulehistory" ("minute", "hour", "day_of_month", "month_of_year", "day_of_week", "timezone", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (OLD."minute", OLD."hour", OLD."day_of_month", OLD."month_of_year", OLD."day_of_week", OLD."timezone", OLD."id", NOW(), \'crontabschedule.before_delete\', OLD."id", _pgh_attach_context()); RETURN NULL;', hash='d75b1d9b42db65b83292e8ca24eacc19cb303440', operation='DELETE', pgid='pgtrigger_crontabschedule_before_delete_bc78e', table='django_celery_beat_crontabschedule', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='eventproxy',
            trigger=pgtrigger.compiler.Trigger(name='event_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."start" IS DISTINCT FROM (NEW."start") OR OLD."end" IS DISTINCT FROM (NEW."end") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."creator_id" IS DISTINCT FROM (NEW."creator_id") OR OLD."created_on" IS DISTINCT FROM (NEW."created_on") OR OLD."updated_on" IS DISTINCT FROM (NEW."updated_on") OR OLD."rule_id" IS DISTINCT FROM (NEW."rule_id") OR OLD."end_recurring_period" IS DISTINCT FROM (NEW."end_recurring_period") OR OLD."calendar_id" IS DISTINCT FROM (NEW."calendar_id") OR OLD."color_event" IS DISTINCT FROM (NEW."color_event") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "occasions_eventhistory" ("start", "end", "title", "description", "creator_id", "created_on", "updated_on", "rule_id", "end_recurring_period", "calendar_id", "color_event", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."start", NEW."end", NEW."title", NEW."description", NEW."creator_id", NEW."created_on", NEW."updated_on", NEW."rule_id", NEW."end_recurring_period", NEW."calendar_id", NEW."color_event", NEW."id", NOW(), \'event.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='8ec820e69ce72060e23b6e270c82c51c7c6c2202', operation='UPDATE', pgid='pgtrigger_event_snapshot_update_1fea0', table='schedule_event', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='eventrelationproxy',
            trigger=pgtrigger.compiler.Trigger(name='eventrelation_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."event_id" IS DISTINCT FROM (NEW."event_id") OR OLD."content_type_id" IS DISTINCT FROM (NEW."content_type_id") OR OLD."object_id" IS DISTINCT FROM (NEW."object_id") OR OLD."distinction" IS DISTINCT FROM (NEW."distinction") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "occasions_eventrelationhistory" ("event_id", "content_type_id", "object_id", "distinction", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."event_id", NEW."content_type_id", NEW."object_id", NEW."distinction", NEW."id", NOW(), \'eventrelation.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='6468996ed6d9b67e5fc2689a3f7b291d10e0140c', operation='UPDATE', pgid='pgtrigger_eventrelation_snapshot_update_0f014', table='schedule_eventrelation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='gathering',
            trigger=pgtrigger.compiler.Trigger(name='gathering_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."meet_id" IS DISTINCT FROM (NEW."meet_id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."start" IS DISTINCT FROM (NEW."start") OR OLD."finish" IS DISTINCT FROM (NEW."finish") OR OLD."site_type_id" IS DISTINCT FROM (NEW."site_type_id") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."site_id" IS DISTINCT FROM (NEW."site_id") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name"))', func='INSERT INTO "occasions_gatheringshistory" ("id", "meet_id", "created", "modified", "is_removed", "start", "finish", "site_type_id", "infos", "site_id", "display_name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."meet_id", NEW."created", NEW."modified", NEW."is_removed", NEW."start", NEW."finish", NEW."site_type_id", NEW."infos", NEW."site_id", NEW."display_name", NOW(), \'gathering.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='bc1a523330bab92335f9d4097f7f729a7849fa1d', operation='UPDATE', pgid='pgtrigger_gathering_snapshot_update_56e8f', table='occasions_gatherings', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='intervalscheduleproxy',
            trigger=pgtrigger.compiler.Trigger(name='intervalschedule_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."every" IS DISTINCT FROM (NEW."every") OR OLD."period" IS DISTINCT FROM (NEW."period") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "occasions_intervalschedulehistory" ("every", "period", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."every", NEW."period", NEW."id", NOW(), \'intervalschedule.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='3263ac90915572d6eb71f3e995e8454a6aff0184', operation='UPDATE', pgid='pgtrigger_intervalschedule_snapshot_update_e7cc2', table='django_celery_beat_intervalschedule', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='meet',
            trigger=pgtrigger.compiler.Trigger(name='meet_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."shown_audience" IS DISTINCT FROM (NEW."shown_audience") OR OLD."audience_editable" IS DISTINCT FROM (NEW."audience_editable") OR OLD."start" IS DISTINCT FROM (NEW."start") OR OLD."finish" IS DISTINCT FROM (NEW."finish") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."site_type_id" IS DISTINCT FROM (NEW."site_type_id") OR OLD."slug" IS DISTINCT FROM (NEW."slug") OR OLD."site_id" IS DISTINCT FROM (NEW."site_id") OR OLD."assembly_id" IS DISTINCT FROM (NEW."assembly_id") OR OLD."major_character_id" IS DISTINCT FROM (NEW."major_character_id") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name"))', func='INSERT INTO "occasions_meetshistory" ("id", "created", "modified", "is_removed", "shown_audience", "audience_editable", "start", "finish", "infos", "site_type_id", "slug", "site_id", "assembly_id", "major_character_id", "display_name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."shown_audience", NEW."audience_editable", NEW."start", NEW."finish", NEW."infos", NEW."site_type_id", NEW."slug", NEW."site_id", NEW."assembly_id", NEW."major_character_id", NEW."display_name", NOW(), \'meet.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='dc93d019f8f47d29ab6232ffcdadf86ab81f6385', operation='UPDATE', pgid='pgtrigger_meet_snapshot_update_a7821', table='occasions_meets', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='messagetemplate',
            trigger=pgtrigger.compiler.Trigger(name='messagetemplate_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."organization_id" IS DISTINCT FROM (NEW."organization_id") OR OLD."templates" IS DISTINCT FROM (NEW."templates") OR OLD."defaults" IS DISTINCT FROM (NEW."defaults") OR OLD."type" IS DISTINCT FROM (NEW."type"))', func='INSERT INTO "occasions_message_templateshistory" ("id", "created", "modified", "is_removed", "organization_id", "templates", "defaults", "type", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."organization_id", NEW."templates", NEW."defaults", NEW."type", NOW(), \'messagetemplate.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='b0ccf42ba967181f5c864aadd78f275d53718d96', operation='UPDATE', pgid='pgtrigger_messagetemplate_snapshot_update_594a2', table='occasions_message_templates', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='occurrenceproxy',
            trigger=pgtrigger.compiler.Trigger(name='occurrence_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."event_id" IS DISTINCT FROM (NEW."event_id") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."start" IS DISTINCT FROM (NEW."start") OR OLD."end" IS DISTINCT FROM (NEW."end") OR OLD."cancelled" IS DISTINCT FROM (NEW."cancelled") OR OLD."original_start" IS DISTINCT FROM (NEW."original_start") OR OLD."original_end" IS DISTINCT FROM (NEW."original_end") OR OLD."created_on" IS DISTINCT FROM (NEW."created_on") OR OLD."updated_on" IS DISTINCT FROM (NEW."updated_on") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "occasions_occurrencehistory" ("event_id", "title", "description", "start", "end", "cancelled", "original_start", "original_end", "created_on", "updated_on", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."event_id", NEW."title", NEW."description", NEW."start", NEW."end", NEW."cancelled", NEW."original_start", NEW."original_end", NEW."created_on", NEW."updated_on", NEW."id", NOW(), \'occurrence.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='f134618efcb3dcb6c0c360ff838f871560db16e4', operation='UPDATE', pgid='pgtrigger_occurrence_snapshot_update_ad4df', table='schedule_occurrence', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='periodictaskproxy',
            trigger=pgtrigger.compiler.Trigger(name='periodictask_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."task" IS DISTINCT FROM (NEW."task") OR OLD."interval_id" IS DISTINCT FROM (NEW."interval_id") OR OLD."crontab_id" IS DISTINCT FROM (NEW."crontab_id") OR OLD."solar_id" IS DISTINCT FROM (NEW."solar_id") OR OLD."clocked_id" IS DISTINCT FROM (NEW."clocked_id") OR OLD."args" IS DISTINCT FROM (NEW."args") OR OLD."kwargs" IS DISTINCT FROM (NEW."kwargs") OR OLD."queue" IS DISTINCT FROM (NEW."queue") OR OLD."exchange" IS DISTINCT FROM (NEW."exchange") OR OLD."routing_key" IS DISTINCT FROM (NEW."routing_key") OR OLD."headers" IS DISTINCT FROM (NEW."headers") OR OLD."priority" IS DISTINCT FROM (NEW."priority") OR OLD."expires" IS DISTINCT FROM (NEW."expires") OR OLD."expire_seconds" IS DISTINCT FROM (NEW."expire_seconds") OR OLD."one_off" IS DISTINCT FROM (NEW."one_off") OR OLD."start_time" IS DISTINCT FROM (NEW."start_time") OR OLD."enabled" IS DISTINCT FROM (NEW."enabled") OR OLD."last_run_at" IS DISTINCT FROM (NEW."last_run_at") OR OLD."total_run_count" IS DISTINCT FROM (NEW."total_run_count") OR OLD."date_changed" IS DISTINCT FROM (NEW."date_changed") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "occasions_periodictaskhistory" ("name", "task", "interval_id", "crontab_id", "solar_id", "clocked_id", "args", "kwargs", "queue", "exchange", "routing_key", "headers", "priority", "expires", "expire_seconds", "one_off", "start_time", "enabled", "last_run_at", "total_run_count", "date_changed", "description", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."name", NEW."task", NEW."interval_id", NEW."crontab_id", NEW."solar_id", NEW."clocked_id", NEW."args", NEW."kwargs", NEW."queue", NEW."exchange", NEW."routing_key", NEW."headers", NEW."priority", NEW."expires", NEW."expire_seconds", NEW."one_off", NEW."start_time", NEW."enabled", NEW."last_run_at", NEW."total_run_count", NEW."date_changed", NEW."description", NEW."id", NOW(), \'periodictask.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='1dde0883a7329f24325b12b739017a59a8597089', operation='UPDATE', pgid='pgtrigger_periodictask_snapshot_update_211a3', table='django_celery_beat_periodictask', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='price',
            trigger=pgtrigger.compiler.Trigger(name='price_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."assembly_id" IS DISTINCT FROM (NEW."assembly_id") OR OLD."start" IS DISTINCT FROM (NEW."start") OR OLD."finish" IS DISTINCT FROM (NEW."finish") OR OLD."price_type" IS DISTINCT FROM (NEW."price_type") OR OLD."price_value" IS DISTINCT FROM (NEW."price_value") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name"))', func='INSERT INTO "occasions_priceshistory" ("id", "created", "modified", "is_removed", "assembly_id", "start", "finish", "price_type", "price_value", "display_name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."assembly_id", NEW."start", NEW."finish", NEW."price_type", NEW."price_value", NEW."display_name", NOW(), \'price.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='92db6c14d6dadb8044f4472c06e08e29e045d87b', operation='UPDATE', pgid='pgtrigger_price_snapshot_update_79b88', table='occasions_prices', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ruleproxy',
            trigger=pgtrigger.compiler.Trigger(name='rule_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."frequency" IS DISTINCT FROM (NEW."frequency") OR OLD."params" IS DISTINCT FROM (NEW."params") OR OLD."id" IS DISTINCT FROM (NEW."id"))', func='INSERT INTO "occasions_rulehistory" ("name", "description", "frequency", "params", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."name", NEW."description", NEW."frequency", NEW."params", NEW."id", NOW(), \'rule.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='796cbf2ae9c02f261b079e26e7ec1b4d65a86837', operation='UPDATE', pgid='pgtrigger_rule_snapshot_update_46a42', table='schedule_rule', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='team',
            trigger=pgtrigger.compiler.Trigger(name='team_snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."meet_id" IS DISTINCT FROM (NEW."meet_id") OR OLD."display_order" IS DISTINCT FROM (NEW."display_order") OR OLD."site_type_id" IS DISTINCT FROM (NEW."site_type_id") OR OLD."infos" IS DISTINCT FROM (NEW."infos") OR OLD."site_id" IS DISTINCT FROM (NEW."site_id") OR OLD."slug" IS DISTINCT FROM (NEW."slug") OR OLD."display_name" IS DISTINCT FROM (NEW."display_name"))', func='INSERT INTO "occasions_teamshistory" ("id", "created", "modified", "is_removed", "meet_id", "display_order", "site_type_id", "infos", "site_id", "slug", "display_name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."meet_id", NEW."display_order", NEW."site_type_id", NEW."infos", NEW."site_id", NEW."slug", NEW."display_name", NOW(), \'team.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;', hash='5c3edbc2bfb112baa23966190f7e55a3aad0d5d4', operation='UPDATE', pgid='pgtrigger_team_snapshot_update_1befd', table='occasions_teams', when='AFTER')),
        ),
    ]
