#!/bin/bash

set -o errexit
set -o nounset
sleep 10  # not needed after docker-compose 1.29 to support depends_on condition of service_completed_successfully

watchgod celery.__main__.main --args -A config.celery_app worker -l INFO
