name: Playwright E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install Node dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Build and Start Django Docker Environment
      run: |
        touch .envs/.local/.sendgrid.env .envs/.local/.mailgun.env
        docker compose -f local.yml build
        docker compose -f local.yml run --rm django python manage.py migrate
        docker compose -f local.yml up -d
        # Wait for PostgreSQL and Django to be fully ready
        sleep 15
        docker compose -f local.yml run --rm django python manage.py update_content_types
        # Load your natural key fixture
        docker compose -f local.yml run --rm django python manage.py loaddata fixtures/ci_seed.json

    - name: Run Playwright tests
      run: npx playwright test
      env:
        BASE_URL: http://127.0.0.1:8008
        C_PASSWORD: ${{ secrets.C_PASSWORD }}

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
